#!/usr/bin/env bash
#
# Formatting gate, scoped to what this change actually touched.
#
# A repo-wide `ruff format --check` would fail today: CI has gated `ruff check`
# since the beginning but never the formatter, so roughly fifty backend files on
# `main` are unformatted (tech-debt #57). Turning the gate on repo-wide has two
# possible outcomes, and both are bad: red CI on every unrelated PR, or a
# reformat-the-world commit that buries every real diff after it in review.
#
# So the gate is scoped to the files the branch changed. Consequences, stated
# plainly:
#
#   * New and edited files are held to the standard from now on, which is the
#     property that matters — the unformatted set can only shrink.
#   * A file nobody touches stays unformatted and stays unchecked. That is the
#     debt, and it is repaid by a dedicated formatting PR, not by this script.
#   * A PR that only moves an already-unformatted file will fail, correctly:
#     if you are editing it, you are formatting it.
#
# Usage: format_changed.sh <base-ref>
# Exits non-zero when a changed file is not formatted, printing the diff.

set -euo pipefail

BASE_REF="${1:-origin/main}"
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# Three-dot: the merge base, so the comparison is "what this branch added" and
# not "everything that landed on main since it was cut".
if git rev-parse --verify --quiet "$BASE_REF" >/dev/null; then
  RANGE="$BASE_REF...HEAD"
else
  echo ">> $BASE_REF not found; falling back to the previous commit"
  RANGE="HEAD~1...HEAD"
fi

# --diff-filter=d drops deletions: a file that no longer exists cannot be
# formatted, and passing its path to the formatter is an error, not a finding.
mapfile -t CHANGED < <(git diff --name-only --diff-filter=d "$RANGE")

if [ ${#CHANGED[@]} -eq 0 ]; then
  echo ">> no changed files in $RANGE — nothing to check"
  exit 0
fi

PY_FILES=()
WEB_FILES=()
for file in "${CHANGED[@]}"; do
  case "$file" in
    backend/*.py) PY_FILES+=("${file#backend/}") ;;
    frontend/*.ts | frontend/*.tsx | frontend/*.js | frontend/*.jsx | frontend/*.mjs)
      WEB_FILES+=("${file#frontend/}")
      ;;
  esac
done

status=0

if [ ${#PY_FILES[@]} -gt 0 ]; then
  echo ">> ruff format --check on ${#PY_FILES[@]} changed backend file(s)"
  ( cd backend && uv run ruff format --check --diff "${PY_FILES[@]}" ) || status=1
else
  echo ">> no changed backend Python files"
fi

# The frontend half is gated ONLY if the repo has actually chosen a Prettier
# configuration. Today it has not: there is no .prettierrc, and Prettier's
# defaults (semicolons, double quotes) are the opposite of the code that exists
# (no semicolons, single quotes) — so a gate here would not be checking the
# project's standard, it would be inventing one and failing every file against
# it. Adopting a config rewrites 55+ files whichever print width is chosen,
# which is a decision and its own PR, not a side effect of this script.
#
# The check activates by itself the moment a config lands. Until then the
# frontend's automated style gate is eslint, which CI already runs at
# --max-warnings 0. Recorded as tech-debt #62.
have_prettier_config=0
for candidate in \
  frontend/.prettierrc frontend/.prettierrc.json frontend/.prettierrc.js \
  frontend/prettier.config.js frontend/prettier.config.mjs .prettierrc .prettierrc.json
do
  [ -f "$candidate" ] && have_prettier_config=1 && break
done

if [ ${#WEB_FILES[@]} -eq 0 ]; then
  echo ">> no changed frontend files"
elif [ "$have_prettier_config" -eq 0 ]; then
  echo ">> ${#WEB_FILES[@]} changed frontend file(s), but no Prettier config exists — skipping"
  echo "   (add frontend/.prettierrc to turn this gate on; see tech-debt #62)"
else
  echo ">> prettier --check on ${#WEB_FILES[@]} changed frontend file(s)"
  # `lib/types.ts` is generated by openapi-typescript and is checked by the
  # contract-drift job instead; formatting it here would fight that job.
  FILTERED=()
  for file in "${WEB_FILES[@]}"; do
    [ "$file" = "lib/types.ts" ] && continue
    FILTERED+=("$file")
  done
  if [ ${#FILTERED[@]} -gt 0 ]; then
    ( cd frontend && npx prettier --check "${FILTERED[@]}" ) || status=1
  fi
fi

if [ "$status" -ne 0 ]; then
  echo
  echo "Formatting gate failed. Fix with:"
  echo "  cd backend  && uv run ruff format <the files you changed>"
  echo "  cd frontend && npx prettier --write <the files you changed>"
fi

exit "$status"
