"""The migration chain itself, exercised against a REAL Postgres.

Nothing tested this before session 21, and the gap had already cost something.
Every other test builds its schema with ``Base.metadata.create_all``, so the
models were the only definition anything checked — and eight indexes had
accumulated that existed *only* in migrations. To ``alembic --autogenerate``
that reads as eight indexes the models want dropped, which is how a routine
"generate the next migration" step quietly proposes ``DROP INDEX`` against
production. The models now declare them, and this module keeps it that way.

Three properties, in the order they matter:

1. ``upgrade head`` runs clean from an empty database.
2. The result matches ``Base.metadata`` exactly — the drift guard. This is the
   test that fails when a model gains a column and no migration does.
3. ``downgrade base`` reverses the whole chain, so a rollback can actually roll
   back (ADR-30's concern, one layer lower).

Runs only when ``TEST_DATABASE_URL`` points at a live Postgres (``make test``
starts one on :5433); otherwise it skips, keeping the default
``uv run pytest`` hermetic and offline.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest
import sqlalchemy as sa
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

from alembic import command
from app.config import get_settings
from app.db.base import Base

TEST_DATABASE_URL = os.environ.get("TEST_DATABASE_URL", "")

pytestmark = pytest.mark.skipif(
    not TEST_DATABASE_URL.startswith("postgresql"),
    reason="TEST_DATABASE_URL is not a Postgres URL (set by `make test`)",
)

BACKEND_DIR = Path(__file__).resolve().parents[1]


@pytest.fixture()
def alembic_config(monkeypatch):
    """Alembic pointed at the test Postgres, against an empty database.

    ``alembic/env.py`` reads the URL from ``get_settings()``, not from
    ``alembic.ini``, so the override goes through the environment and the
    settings cache is cleared on both sides of the test. The config is built
    programmatically (no ``config_file_name``) so env.py skips ``fileConfig``
    and does not reconfigure pytest's logging.
    """

    engine = sa.create_engine(TEST_DATABASE_URL, future=True)
    try:
        engine.connect().close()
    except Exception as exc:  # pragma: no cover - infra guard
        engine.dispose()
        pytest.skip(f"Postgres unreachable at TEST_DATABASE_URL: {exc}")

    monkeypatch.setenv("DATABASE_URL", TEST_DATABASE_URL)
    get_settings.cache_clear()

    _wipe(engine)

    config = Config()
    config.set_main_option("script_location", str(BACKEND_DIR / "alembic"))

    try:
        yield config
    finally:
        _wipe(engine)
        engine.dispose()
        get_settings.cache_clear()


def _wipe(engine: sa.Engine) -> None:
    """Drop every table, including alembic's own version bookkeeping.

    ``Base.metadata.drop_all`` cannot remove ``alembic_version`` (it is not a
    model), and leaving it behind would make the next run believe the database
    is already at head.
    """

    Base.metadata.drop_all(engine)
    with engine.begin() as connection:
        connection.execute(sa.text("DROP TABLE IF EXISTS alembic_version"))


def _table_names(engine: sa.Engine) -> set[str]:
    return set(sa.inspect(engine).get_table_names())


def test_upgrade_head_builds_the_whole_schema_from_empty(alembic_config):
    engine = sa.create_engine(TEST_DATABASE_URL, future=True)
    try:
        assert _table_names(engine) == set()

        command.upgrade(alembic_config, "head")

        built = _table_names(engine)
        expected = set(Base.metadata.tables) | {"alembic_version"}
        assert built == expected
    finally:
        engine.dispose()


def test_migrated_schema_matches_the_models(alembic_config):
    """The drift guard: a migrated database must satisfy ``alembic check``.

    ``command.check`` autogenerates against the live database and raises when it
    finds anything to do. A model changed without a migration fails here, and so
    does a migration that creates something the models never declare — the
    direction that had already gone wrong eight times.
    """

    command.upgrade(alembic_config, "head")

    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(
            "models and migrations have drifted — `alembic check` found pending "
            f"operations. Declare them in one place or add a migration:\n{exc}"
        )


def test_downgrade_base_reverses_every_migration(alembic_config):
    engine = sa.create_engine(TEST_DATABASE_URL, future=True)
    try:
        command.upgrade(alembic_config, "head")
        assert _table_names(engine) - {"alembic_version"} != set()

        command.downgrade(alembic_config, "base")

        # alembic_version survives a downgrade to base, empty; nothing else may.
        assert _table_names(engine) - {"alembic_version"} == set()
    finally:
        engine.dispose()
