"""SQLAlchemy models — the four tables from the SPEC.

Design note: the models are deliberately SQLite-compatible so most tests run
against an in-memory SQLite database. The only Postgres-specific type is the
``kyc`` JSONB column, declared with ``.with_variant`` so it degrades to plain
JSON on SQLite. Timestamps use Python-side defaults (``_utcnow``) rather than
DB ``now()`` so ``create_all`` works on SQLite; the Alembic migration adds
server-side defaults for Postgres.
"""

import uuid
from datetime import UTC, datetime
from decimal import Decimal
from typing import Any, Literal

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


def _utcnow() -> datetime:
    return datetime.now(UTC)


class Analysis(Base):
    """One analysis run. This table doubles as the job queue (see jobs/queue.py)."""

    __tablename__ = "analyses"
    __table_args__ = (
        # Declared here as well as in the migrations, deliberately. The models are
        # the metadata `alembic check`/`--autogenerate` compares a live database
        # against, and every index that exists only in a migration reads to
        # autogenerate as one the models want DROPPED. Eight of them had accumulated
        # that way (session 21); an autogenerated migration would have quietly
        # dropped this table's queue and checker-reuse indexes in production.
        sa.Index("ix_analyses_status_created", "status", "created_at"),
        sa.Index(
            "ix_analyses_checker_reuse",
            "kind",
            "status",
            "brand",
            "category",
            "lang",
            "created_at",
        ),
        sa.Index("ix_analyses_created_by_user_id", "created_by_user_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    # Tenancy (P7.1). Nullable, and with **no ForeignKey and no index**, all
    # three deliberate.
    #
    # NULL means the PUBLIC scope. The product's whole live surface is
    # anonymous — all 47 analyses in production on 2026-08-05 were submitted by
    # nobody, and this table has never had a user column — so NULL is the
    # overwhelmingly common value and a real one, not an unfinished backfill.
    #
    # No FK, because of what the FK's delete rule would have to be. `SET NULL`
    # is actively unsafe here: NULL is world-readable, so deleting an
    # organization would silently *republish* every private analysis it owned.
    # When owned analyses arrive (M4) the FK must be added as **ON DELETE
    # RESTRICT** — org deletion is then forced through an explicit reassign or
    # purge. That standing constraint is recorded in ADR-35; deferring the FK
    # keeps it from being got wrong by default now.
    #
    # No index, because this is the hot queue table and every row's value is
    # NULL: a btree over one repeated value earns nothing and an FK validation
    # scan would take ACCESS EXCLUSIVE on the shared box for no benefit.
    org_id: Mapped[uuid.UUID | None] = mapped_column(sa.Uuid, nullable=True)
    # The authenticated user who queued this run (user-scoped history + limits).
    # NULL on pre-backfill rows and any future non-user callers. No FK yet — see
    # org_id note above; user plan / org billing may replace this interim gate.
    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(sa.Uuid, nullable=True)
    url: Mapped[str] = mapped_column(sa.Text, nullable=False)
    status: Mapped[str] = mapped_column(sa.Text, nullable=False, default="queued")
    progress: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0)
    current_step: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    error: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    # Salted hash of the submitter's client IP (P5.0 rate limiting). Nullable:
    # rows created before this column, and any future non-HTTP callers, leave it
    # null. Never stores the raw IP.
    ip_hash: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    # Checker fields (P5.1). All nullable/defaulted so existing MVP rows are
    # untouched. ``kind`` distinguishes an MVP crawl analysis ('mvp') from a
    # checker analysis ('checker'); brand/category/lang are stored NORMALIZED
    # (trim + casefold) on checker rows so the 24h reuse lookup is a plain
    # equality match. They stay null on MVP rows.
    kind: Mapped[str] = mapped_column(sa.Text, nullable=True, default="mvp", server_default="mvp")
    # quick = one-shot six-step run (default). guided = pause after prompts for
    # KYC/prompt review before execute (ADR-50).
    run_mode: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="quick", server_default="quick"
    )
    brand: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    category: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    lang: Mapped[str] = mapped_column(sa.Text, nullable=True, default="en", server_default="en")
    kyc: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    # Provider spend incurred before prompt responses exist.  Today this is the
    # KYC extraction (and its one bounded repair retry); keeping it separate
    # prevents ``responses.cost_usd`` from pretending to be the whole run.
    kyc_cost_usd: Mapped[Decimal] = mapped_column(
        sa.Numeric(10, 6), nullable=False, default=0, server_default="0"
    )
    kyc_usage: Mapped[list[Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    # Composite GEO score on a 0–100 scale (mention × position × citation ×
    # sentiment). Legacy MVP rows may still hold a 0–1 mention-rate fraction.
    geo_score: Mapped[float | None] = mapped_column(sa.Float, nullable=True)
    footprint_count: Mapped[int | None] = mapped_column(sa.Integer, nullable=True)
    total_responses: Mapped[int | None] = mapped_column(sa.Integer, nullable=True)
    # SERP visibility (ADR-28). All nullable, and they stay null on every run
    # where SERP was switched off or could not be measured — which is the point:
    # a null here means "we did not measure", and only a number means "we did".
    # ``serp_query_count`` counts the queries that produced a *usable* page, so
    # ``serp_score == serp_hit_count / serp_query_count`` always holds.
    serp_score: Mapped[float | None] = mapped_column(sa.Float, nullable=True)
    serp_hit_count: Mapped[int | None] = mapped_column(sa.Integer, nullable=True)
    serp_query_count: Mapped[int | None] = mapped_column(sa.Integer, nullable=True)
    serp_status: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    serp_source: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    # SEO / AI-readiness audit (ADR-31). Null on every run that did not audit —
    # the same discipline as the serp_* columns above. ``seo_grade`` is the
    # headline because a weighted average can hide a fatal problem; the score is
    # the supporting number and the failing checks are the real output.
    seo_score: Mapped[float | None] = mapped_column(sa.Float, nullable=True)
    seo_grade: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    seo_status: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    reliability_score: Mapped[float | None] = mapped_column(sa.Float, nullable=True)
    interventions: Mapped[list[Any] | dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    # Rolled-up citation metrics across geo_records / responses.audit for this run.
    citation_summary: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    claimed_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)
    attempts: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    prompts: Mapped[list["Prompt"]] = relationship(
        cascade="all, delete-orphan", order_by="Prompt.created_at"
    )
    responses: Mapped[list["Response"]] = relationship(
        cascade="all, delete-orphan", order_by="Response.created_at"
    )
    serp_checks: Mapped[list["SerpCheck"]] = relationship(
        cascade="all, delete-orphan", order_by="SerpCheck.created_at"
    )
    seo_checks: Mapped[list["SeoCheck"]] = relationship(
        cascade="all, delete-orphan", order_by="SeoCheck.created_at"
    )
    geo_records: Mapped[list["GeoRecord"]] = relationship(
        cascade="all, delete-orphan", order_by="GeoRecord.created_at"
    )


class Prompt(Base):
    __tablename__ = "prompts"

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    analysis_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("analyses.id", ondelete="CASCADE"), nullable=False
    )
    text: Mapped[str] = mapped_column(sa.Text, nullable=False)
    category: Mapped[str] = mapped_column(sa.Text, nullable=False)
    # Provenance for guided edits and future prompt-generation training.
    # generated | edited | user — see app.services.guided_prompts.
    source: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="generated", server_default="generated"
    )
    # When true, PATCH /prompts must include the row unchanged (future: core probes).
    locked: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, default=False, server_default=sa.false()
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )


class Response(Base):
    __tablename__ = "responses"

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    analysis_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("analyses.id", ondelete="CASCADE"), nullable=False
    )
    prompt_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("prompts.id", ondelete="CASCADE"), nullable=False
    )
    engine: Mapped[str] = mapped_column(sa.Text, nullable=False)
    model: Mapped[str] = mapped_column(sa.Text, nullable=False)
    raw_text: Mapped[str] = mapped_column(sa.Text, nullable=False)
    footprint: Mapped[bool | None] = mapped_column(sa.Boolean, nullable=True)
    matched_snippet: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    # Measured-audit payload (search_visibility, citations, gaps, …). Null on
    # legacy multi-engine panel rows.
    audit: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    cost_usd: Mapped[Decimal] = mapped_column(sa.Numeric(10, 6), nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )


class SerpCheck(Base):
    """One search query run for an analysis, and what the results page showed.

    Stored rather than recomputed, for two reasons. The product's wedge is
    showing its work, so the evidence behind the SERP number — which query, which
    result, at what rank — has to be one click away like every raw LLM answer
    already is. And a SERP is a snapshot of something that moves: running the
    same query tomorrow answers a different question, so the observation is only
    meaningful with the moment attached.

    ``hit`` is deliberately nullable. NULL means the page could not be measured
    (every upstream engine refused, or the instance was unreachable) and is
    excluded from the score entirely; ``False`` is a real, counted miss.
    """

    __tablename__ = "serp_checks"
    # See the note on Analysis.__table_args__ for why migration-created indexes
    # are mirrored here.
    __table_args__ = (sa.Index("ix_serp_checks_analysis_id", "analysis_id"),)

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    analysis_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("analyses.id", ondelete="CASCADE"), nullable=False
    )
    query: Mapped[str] = mapped_column(sa.Text, nullable=False)
    source: Mapped[str] = mapped_column(sa.Text, nullable=False)
    hit: Mapped[bool | None] = mapped_column(sa.Boolean, nullable=True)
    rank: Mapped[int | None] = mapped_column(sa.Integer, nullable=True)
    matched_url: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    matched_snippet: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    # 'domain' (the company's own site ranked) or 'text' (something else's page
    # named it). Null on a miss or an unmeasurable page.
    matched_via: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    result_count: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0)
    # Comma-joined engine names that refused to answer this query. Plain Text
    # rather than JSON because it is a diagnostic breadcrumb, not a queryable
    # structure, and Text keeps the model SQLite-compatible (see module docstring).
    unresponsive_engines: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )


class SeoCheck(Base):
    """One SEO / AI-readiness check for an analysis, and its evidence (ADR-31).

    Stored per check rather than as one JSON blob, for the same reason
    ``serp_checks`` is: the product's wedge is showing its work, so "why is this
    site invisible" has to be one click away — and because the interesting
    product question is cross-sectional ("how many sites block GPTBot?"), which a
    blob cannot answer.

    ``status`` carries five values, not two. ``not_measured`` (the input was
    unreadable) and ``not_applicable`` (the check does not apply here) are both
    excluded from the score, and are deliberately distinct from each other and
    from ``fail`` — the UI says something different for each.
    """

    __tablename__ = "seo_checks"
    # See the note on Analysis.__table_args__.
    __table_args__ = (
        sa.Index("ix_seo_checks_analysis_id", "analysis_id"),
        sa.Index("ix_seo_checks_check_id_status", "check_id", "status"),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    analysis_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("analyses.id", ondelete="CASCADE"), nullable=False
    )
    # Stable identifier for the check, e.g. 'ai_crawler_access'. Plain text
    # rather than an enum: the catalogue will gain and lose checks between
    # releases, and a stored row must stay readable when its check is retired.
    check_id: Mapped[str] = mapped_column(sa.Text, nullable=False)
    title: Mapped[str] = mapped_column(sa.Text, nullable=False)
    severity: Mapped[str] = mapped_column(sa.Text, nullable=False)
    status: Mapped[str] = mapped_column(sa.Text, nullable=False)
    detail: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    evidence: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )


class GeoRecord(Base):
    """Columnar copy of one Kaira-style measured/simulated audit record.

    Mirrors ``merge_measured_record`` / simulated output keys so brand-level
    visualizations and later models can query without digging into
    ``responses.audit``. One row per prompt response.
    """

    __tablename__ = "geo_records"

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    analysis_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("analyses.id", ondelete="CASCADE"), nullable=False, index=True
    )
    response_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("responses.id", ondelete="CASCADE"), nullable=False, unique=True
    )
    brand: Mapped[str] = mapped_column(sa.Text, nullable=False)
    sector: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    prompt: Mapped[str] = mapped_column(sa.Text, nullable=False)
    prompt_group: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    intent: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    measurement_mode: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    search_provider: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    search_results: Mapped[list[Any] | dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    search_visibility: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    grounded_answer: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    simulated_answer: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    mentioned: Mapped[bool | None] = mapped_column(sa.Boolean, nullable=True)
    rank_position: Mapped[int | None] = mapped_column(sa.Integer, nullable=True)
    mention_context: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    competitors: Mapped[list[Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    answer_summary: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    recommendation_reasoning: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    reasoning_trace: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    citations: Mapped[list[Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    citation_metrics: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    visibility_drivers: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    visibility_gaps: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    trust_signals: Mapped[list[Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    entities_associated_with_brand: Mapped[list[Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    sentiment: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    content_improvement_opportunities: Mapped[list[Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    model: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    generated_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)
    error: Mapped[bool | None] = mapped_column(sa.Boolean, nullable=True)
    schema_version: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    owned_domains: Mapped[list[Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )


class CheckerSubmission(Base):
    """One accepted checker submit (P5.1) — append-only demand signal + lead.

    The 24h cache shares a single ``analyses`` row across visitors, so leads and
    demand must be counted per submit here rather than on the analysis. Every
    accepted submit (cache hits included) inserts a row; ``email`` is filled
    later by ``POST /api/v1/checker/leads`` for that specific row, so two
    visitors served the same cached analysis each keep their own lead.
    """

    __tablename__ = "checker_submissions"
    # See the note on Analysis.__table_args__.
    __table_args__ = (sa.Index("ix_checker_submissions_analysis_id", "analysis_id"),)

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    analysis_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("analyses.id", ondelete="CASCADE"), nullable=False
    )
    # Salted client-IP hash — stays null in P5.1; P5.6 populates it (owns salt).
    ip_hash: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    lang: Mapped[str] = mapped_column(sa.Text, nullable=False)
    email: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )


class WaitlistSignup(Base):
    """One waitlist signup (P5.13) — a landing-page email capture.

    ``email`` is stored NORMALIZED (trim + lowercase) and is UNIQUE, so the
    submit path is an ``INSERT ... ON CONFLICT DO NOTHING RETURNING id``: a
    returned row means a genuinely new signup (which triggers the thank-you +
    notification emails), a null return means a duplicate (still answered 202,
    no enumeration). ``ip_hash`` reuses the existing salted-hash helper and stays
    null for any non-HTTP caller; the raw IP is never stored.
    """

    __tablename__ = "waitlist_signups"

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    email: Mapped[str] = mapped_column(sa.Text, nullable=False, unique=True)
    ip_hash: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )


class User(Base):
    """A registered user account."""

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid,
        primary_key=True,
        default=uuid.uuid4,
    )
    email: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        unique=True,
    )
    # Absent for an account created through Google or Apple: there is no
    # password to hash, and storing an unusable placeholder would make
    # "can this account sign in with a password?" unanswerable.
    password_hash: Mapped[str | None] = mapped_column(
        sa.Text,
        nullable=True,
    )
    # The identity provider and its immutable id for this account. Kept because
    # an email can change at the provider while the subject cannot, so the
    # subject is what keeps the returning user attached to their own data.
    auth_provider: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    auth_subject: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    # 'active' | 'disabled'. An administrator disabling an account must stop it
    # logging in, which is a different thing from deleting it: the history, the
    # audit trail and the org membership all survive, and re-enabling restores
    # access rather than recreating a person.
    status: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="active", server_default="active"
    )
    last_active_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
    )
    __table_args__ = (
        sa.UniqueConstraint("auth_provider", "auth_subject", name="uq_users_auth_provider_subject"),
    )


class Organization(Base):
    """A tenant — the billing and security boundary (M1 / P7.1).

    Every signed-in user has at least one: signup creates a **personal org**, so
    "a user" is never a thing that owns data directly. That indirection is the
    whole point — converting a solo account into a company account later is then
    a membership change, not a data migration (baseline §10.4).

    ``slug`` is the human-facing identifier and is globally unique. ``region`` is
    recorded from day one although nothing reads it yet: data residency is an M8
    promise, and adding the column to a populated table later is exactly the
    migration this card exists to avoid.
    """

    __tablename__ = "organizations"
    __table_args__ = (
        # "Exactly one personal org per user" is an invariant the product relies
        # on, so the database enforces it rather than the service layer hoping.
        # It also closes the signup race a get-or-create cannot: two concurrent
        # requests for the same new user both see no org, both insert, and one
        # loses here instead of minting a second home.
        sa.Index(
            "uq_organizations_personal_owner",
            "owner_user_id",
            unique=True,
            postgresql_where=sa.text("kind = 'personal'"),
            sqlite_where=sa.text("kind = 'personal'"),
        ),
        sa.Index("ix_organizations_status", "status"),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(sa.Text, nullable=False)
    slug: Mapped[str] = mapped_column(sa.Text, nullable=False, unique=True)
    # 'active' | 'trial' | 'suspended' | 'closed'. Plain Text, like every other
    # status column here: a stored row must stay readable when the set changes.
    status: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="active", server_default="active"
    )
    region: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    # 'personal' (auto-created at signup) | 'company' (converted or created
    # outright) | 'system' (the reserved public org — see PUBLIC_ORG_ID). Three
    # values rather than a boolean because 'system' is genuinely a third thing,
    # and because the conversion wizard needs to tell "one human" from "a
    # company that happens to have one member" without counting members.
    kind: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="personal", server_default="personal"
    )
    # SET NULL, not CASCADE: deleting the owning user must never silently delete
    # an organization and everything under it. Ownership transfer is P7.5's job;
    # until then an ownerless org is a visible problem rather than a vanished one.
    owner_user_id: Mapped[uuid.UUID | None] = mapped_column(
        sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )


class Workspace(Base):
    """A lane inside an organization — a client for agencies, a brand or region
    for multi-location businesses.

    Workspaces exist in M1 rather than later because the wedge depends on them
    (differentiator D4: free client seats, workspace-per-client).
    """

    __tablename__ = "workspaces"
    __table_args__ = (
        sa.UniqueConstraint("org_id", "slug", name="uq_workspaces_org_slug"),
        sa.Index("ix_workspaces_org_id", "org_id"),
        # "Which workspace do new projects land in?" must have exactly one
        # answer. Picking the oldest row works until two share a timestamp — a
        # retried backfill is enough — after which the answer is whatever the
        # planner felt like. The database settles it instead.
        sa.Index(
            "uq_workspaces_one_default_per_org",
            "org_id",
            unique=True,
            postgresql_where=sa.text("is_default"),
            sqlite_where=sa.text("is_default"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    org_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(sa.Text, nullable=False)
    slug: Mapped[str] = mapped_column(sa.Text, nullable=False)
    is_default: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, default=False, server_default=sa.false()
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )


class Membership(Base):
    """One user's place in one organization, and the role they hold there.

    Multi-org membership is supported from the start (contractor mode, baseline
    §10.4): the unique constraint is on the *pair*, not on ``user_id``.

    ``role`` is deliberately plain Text with **no CHECK constraint**. M8 turns
    roles into data (custom roles by clone-and-edit), so a database-level
    enumeration would guarantee a migration for every role the product ever
    adds. Validation lives in the service layer, where P7.2 puts the permission
    model that actually interprets these strings.
    """

    __tablename__ = "memberships"
    __table_args__ = (
        sa.UniqueConstraint("org_id", "user_id", name="uq_memberships_org_user"),
        sa.Index("ix_memberships_user_id", "user_id"),
        sa.Index("ix_memberships_org_id", "org_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    org_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    role: Mapped[str] = mapped_column(sa.Text, nullable=False)
    # 'invited' | 'active' | 'deactivated'
    status: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="active", server_default="active"
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )


class Invitation(Base):
    """An outstanding offer of a seat in an organization (P7.4).

    An invitation is the only way a person joins an organization they did not
    create, so it is also the only way a role is granted to someone who does not
    yet have an account. That makes it a security object, and three columns carry
    the weight.

    ``token_hash`` stores a SHA-256 of the token, never the token. The plaintext
    exists exactly once — in the email — for the same reason the session module
    stores a hash of the refresh token: a leaked database must not become a set
    of working invitations. Unique, so a token identifies at most one row and the
    lookup is an index hit rather than a scan-and-compare.

    ``expires_at`` is required, not optional. An invitation that never expires is
    a permanent, unrevoked credential sitting in somebody's inbox.

    ``status`` moves ``pending → accepted | revoked`` and never back. Expiry is
    NOT a status: it is derived from ``expires_at`` at read time, because a
    status column would need a sweeper to stay honest and would be wrong between
    sweeps. The partial unique index below therefore keys on ``pending``, which
    lets an org re-invite an address whose earlier invitation was revoked or
    used, while refusing two live invitations to the same person.
    """

    __tablename__ = "invitations"
    __table_args__ = (
        # One live invitation per address per org. Partial, so accepted and
        # revoked rows accumulate as history without blocking a re-invite.
        sa.Index(
            "uq_invitations_pending_org_email",
            "org_id",
            "email",
            unique=True,
            postgresql_where=sa.text("status = 'pending'"),
            sqlite_where=sa.text("status = 'pending'"),
        ),
        sa.Index("ix_invitations_org_status", "org_id", "status"),
        sa.Index("ix_invitations_email", "email"),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    org_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False
    )
    # The workspace the invited role is scoped to, for the workspace-level roles.
    # Nullable because org-level roles (admin, billing_admin) are not scoped to
    # one, and because M1 grants at org grain — the column is here so M8's scope
    # grants do not need a migration on a populated table.
    workspace_id: Mapped[uuid.UUID | None] = mapped_column(
        sa.ForeignKey("workspaces.id", ondelete="SET NULL"), nullable=True
    )
    email: Mapped[str] = mapped_column(sa.Text, nullable=False)
    role: Mapped[str] = mapped_column(sa.Text, nullable=False)
    token_hash: Mapped[str] = mapped_column(sa.Text, nullable=False, unique=True)
    # SET NULL: an invitation must survive the departure of whoever sent it, or
    # the audit question "who let this person in?" loses its answer precisely
    # when it is being asked.
    invited_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    # 'pending' | 'accepted' | 'revoked'. Expiry is derived, not stored.
    status: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="pending", server_default="pending"
    )
    expires_at: Mapped[datetime] = mapped_column(sa.DateTime(timezone=True), nullable=False)
    accepted_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)
    accepted_user_id: Mapped[uuid.UUID | None] = mapped_column(
        sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    revoked_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)
    # Resending mints a NEW token and invalidates the old one, so this is a
    # count of how many times that happened rather than of emails sent.
    sent_count: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, default=1, server_default="1"
    )
    last_sent_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )


class Project(Base):
    """A tracked business inside a workspace: one domain, watched over time.

    This is the anchor every later module hangs from — Site Audit runs, backlink
    profiles (Phase 8), rank tracking, scheduled analyses. It is deliberately
    **not** a rename of ``seo_projects``: that table is the Site Audit module's
    own row and keeps its identity, gaining a ``project_id`` that points here.
    Renaming a populated table on an auto-deploying production database to save
    one join is the trade this card exists to refuse.

    ``domain_key`` repeats ``seo_projects``' normalization (host, no leading
    ``www.``) so one tracked business cannot become two through a URL spelling.
    """

    __tablename__ = "projects"
    __table_args__ = (
        sa.UniqueConstraint("org_id", "domain_key", name="uq_projects_org_domain_key"),
        sa.Index("ix_projects_org_id", "org_id"),
        sa.Index("ix_projects_workspace_id", "workspace_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    # RESTRICT, matching seo_projects: an organization holding tracked
    # businesses cannot be deleted out from under them. P7.7 owns org deletion
    # and must reassign or purge explicitly.
    org_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("organizations.id", ondelete="RESTRICT"), nullable=False
    )
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(sa.Text, nullable=False)
    domain: Mapped[str] = mapped_column(sa.Text, nullable=False)
    domain_key: Mapped[str] = mapped_column(sa.Text, nullable=False)
    locale: Mapped[str] = mapped_column(sa.Text, nullable=False, default="en", server_default="en")
    # 'active' | 'paused' | 'archived'
    status: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="active", server_default="active"
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )


class SeoProject(Base):
    """One user-owned domain that can have many Site Audit runs.

    Projects are deliberately separate from ``analyses``. A GEO analysis is a
    one-off AI visibility measurement; an SEO project is a durable user-owned
    domain whose technical audit can be run repeatedly over time.
    """

    __tablename__ = "seo_projects"
    __table_args__ = (
        sa.UniqueConstraint(
            "user_id",
            "domain_key",
            name="uq_seo_projects_user_domain_key",
        ),
        sa.Index("ix_seo_projects_org_id", "org_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Tenancy (P7.1). Nullable at the database level only because the migration
    # adds the columns before it fills them — every row is backfilled in the
    # same migration, and the service layer writes all three on create. They are
    # not left nullable because "some rows have no org": a Site Audit project
    # always belongs to the org of the user who made it.
    #
    # ``org_id`` is denormalized here rather than reached through ``project_id``
    # so org scoping stays a single predicate on the table being queried. That
    # is what makes the scoping helper cheap enough that nobody is tempted to
    # skip it, and what a Postgres RLS policy would key on later.
    #
    # RESTRICT, not CASCADE: deleting an organization must not silently take a
    # customer's projects and audit history with it. P7.7 owns org deletion and
    # will reassign or purge explicitly; until then the database refuses, which
    # is the failure mode you want on a shared production box.
    org_id: Mapped[uuid.UUID | None] = mapped_column(
        sa.ForeignKey("organizations.id", ondelete="RESTRICT"), nullable=True
    )
    workspace_id: Mapped[uuid.UUID | None] = mapped_column(
        sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=True
    )
    project_id: Mapped[uuid.UUID | None] = mapped_column(
        sa.ForeignKey("projects.id", ondelete="SET NULL"), nullable=True
    )
    name: Mapped[str] = mapped_column(sa.Text, nullable=False)
    domain: Mapped[str] = mapped_column(sa.Text, nullable=False)
    # Normalized host[:port], with a leading ``www.`` removed. This is the
    # per-user identity key, so https://example.com and https://www.example.com
    # cannot quietly become two projects for the same site.
    domain_key: Mapped[str] = mapped_column(sa.Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    audits: Mapped[list["SiteAudit"]] = relationship(
        cascade="all, delete-orphan",
        back_populates="project",
        order_by="SiteAudit.created_at",
    )


class SiteAudit(Base):
    """One durable crawl job for an SEO project.

    This table is a queue independent from ``analyses`` so browser-heavy site
    crawls can be claimed by a dedicated worker without delaying GEO jobs.
    """

    __tablename__ = "site_audits"
    __table_args__ = (
        sa.CheckConstraint(
            "page_limit BETWEEN 1 AND 500",
            name="ck_site_audits_page_limit",
        ),
        sa.CheckConstraint(
            "progress BETWEEN 0 AND 100",
            name="ck_site_audits_progress",
        ),
        sa.CheckConstraint(
            "health_score IS NULL OR health_score BETWEEN 0 AND 100",
            name="ck_site_audits_health_score",
        ),
        # The service checks first for a friendly 409; this database invariant
        # closes the race between two concurrent rerun requests.
        sa.Index(
            "uq_site_audits_one_active_per_project",
            "project_id",
            unique=True,
            postgresql_where=sa.text("status IN ('queued', 'running')"),
            sqlite_where=sa.text("status IN ('queued', 'running')"),
        ),
        # See the note on Analysis.__table_args__ — these two were migration-only.
        sa.Index("ix_site_audits_project_created_at", "project_id", "created_at"),
        sa.Index("ix_site_audits_queue", "status", "claimed_at", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    project_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("seo_projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # No org column here, on purpose. A site audit is reachable only through its
    # project, which is org-scoped, so the join already answers "whose is this?"
    # — and `get_org_audit` makes that join. Denormalizing org onto children
    # costs a backfill and creates one more place to forget; it earns its keep
    # only when a query genuinely starts at the child, which none does yet.
    status: Mapped[Literal["queued", "running", "done", "failed"]] = mapped_column(
        sa.Text, nullable=False, default="queued"
    )
    progress: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0)
    current_step: Mapped[Literal["discovery", "crawl", "analysis", "finalize"] | None] = (
        mapped_column(sa.Text, nullable=True)
    )
    error: Mapped[str | None] = mapped_column(sa.Text, nullable=True)

    page_limit: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=10)
    profile_id: Mapped[Literal["site_audit_mobile", "site_audit_desktop"]] = mapped_column(
        sa.Text, nullable=False, default="site_audit_mobile"
    )
    js_rendering: Mapped[bool] = mapped_column(sa.Boolean, nullable=False, default=True)

    pages_discovered: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0)
    pages_crawled: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0)
    total_errors: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0)
    total_warnings: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0)
    total_notices: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0)
    health_score: Mapped[int | None] = mapped_column(sa.Integer, nullable=True)

    claimed_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)
    started_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)
    attempts: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    project: Mapped[SeoProject] = relationship(back_populates="audits")
    pages: Mapped[list["SiteAuditPage"]] = relationship(
        cascade="all, delete-orphan",
        back_populates="audit",
        order_by="SiteAuditPage.created_at",
    )


class SiteAuditPage(Base):
    """One page snapshot and its structured findings within a Site Audit."""

    __tablename__ = "site_audit_pages"
    __table_args__ = (
        sa.UniqueConstraint(
            "audit_id",
            "final_url",
            name="uq_site_audit_pages_audit_final_url",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    audit_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("site_audits.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    requested_url: Mapped[str] = mapped_column(sa.Text, nullable=False)
    final_url: Mapped[str] = mapped_column(sa.Text, nullable=False)
    status_code: Mapped[int] = mapped_column(sa.Integer, nullable=False)
    title: Mapped[str] = mapped_column(sa.Text, nullable=False, default="")
    h1_count: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0)
    meta_description: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    html_lang: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    # Findings use stable codes and structured details rather than display text
    # as identity. This lets the UI group "missing_image_alt" across pages even
    # when each page has a different missing-image count.
    issues: Mapped[list[dict[str, Any]]] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=False, default=list
    )
    schemas: Mapped[list[dict[str, Any]]] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=False, default=list
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )

    audit: Mapped[SiteAudit] = relationship(back_populates="pages")


class AuthSession(Base):
    """One refresh-token generation within a device/session family.

    Every successful login starts a new ``family_id``. Refresh rotation consumes
    the current row and creates a successor with the same family id. Reuse of a
    consumed refresh token revokes the whole family.
    """

    __tablename__ = "auth_sessions"

    id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid,
        primary_key=True,
        default=uuid.uuid4,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    family_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid,
        nullable=False,
        default=uuid.uuid4,
        index=True,
    )
    refresh_jti_hash: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        unique=True,
    )
    replaced_by_id: Mapped[uuid.UUID | None] = mapped_column(
        sa.ForeignKey("auth_sessions.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
    )
    expires_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=False,
    )
    consumed_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=True,
    )
    revoked_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=True,
    )


class LlmCache(Base):
    __tablename__ = "llm_cache"

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    cache_key: Mapped[str] = mapped_column(sa.Text, nullable=False, unique=True)
    engine: Mapped[str] = mapped_column(sa.Text, nullable=False)
    model: Mapped[str] = mapped_column(sa.Text, nullable=False)
    response_text: Mapped[str] = mapped_column(sa.Text, nullable=False)
    cost_usd: Mapped[Decimal] = mapped_column(sa.Numeric(10, 6), nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )


# ---------------------------------------------------------------------------
# Backlink Intelligence (Phase 8 / roadmap M2)
# ---------------------------------------------------------------------------


class BacklinkCompetitor(Base):
    """A competitor DOMAIN tracked for one project.

    Distinct from the competitor *names* KYC already extracts: a name is a
    discovery seed, and turning "Acme" into ``acme.com`` is a classification
    problem nothing here solves reliably. So a tracked competitor is supplied
    explicitly, and the KYC name rides along as ``label`` when one matched.
    """

    __tablename__ = "backlink_competitors"
    __table_args__ = (
        sa.UniqueConstraint("project_id", "competitor_domain", name="uq_backlink_competitors"),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    org_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    competitor_domain: Mapped[str] = mapped_column(sa.Text, nullable=False)
    label: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    active: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, default=True, server_default=sa.true()
    )
    tracked_since: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )


class BacklinkImport(Base):
    """One refresh of one (project, subject domain) — the queue AND the history.

    Two jobs in one small row, following the house idiom that the table *is* the
    queue (``analyses``, ``site_audits``):

    * **Queue.** Status/claim columns, with a partial index so the scan stays
      tiny however much history accumulates, and a partial unique that makes a
      second concurrent refresh of the same subject impossible.
    * **Analytical snapshot, kept forever.** Coverage, cost, the vendor's
      reported totals, the period deltas, and the decomposed authority score.
      Because history lives here rather than in the link rows, trends survive
      both per-plan row pruning and a change of vendor — the two things that
      would otherwise rewrite the past.
    """

    __tablename__ = "backlink_imports"
    __table_args__ = (
        sa.Index(
            "ix_backlink_imports_queue",
            "status",
            "claimed_at",
            "created_at",
            postgresql_where=sa.text("status IN ('queued', 'running')"),
            sqlite_where=sa.text("status IN ('queued', 'running')"),
        ),
        sa.Index(
            "uq_backlink_imports_one_active",
            "project_id",
            "subject_domain",
            unique=True,
            postgresql_where=sa.text("status IN ('queued', 'running')"),
            sqlite_where=sa.text("status IN ('queued', 'running')"),
        ),
        sa.Index("ix_backlink_imports_series", "project_id", "subject_domain", "snapshot_at"),
        sa.CheckConstraint("attempts >= 0", name="ck_backlink_imports_attempts"),
        sa.CheckConstraint(
            "yanki_authority IS NULL OR yanki_authority BETWEEN 0 AND 100",
            name="ck_backlink_imports_authority",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    org_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    subject_domain: Mapped[str] = mapped_column(sa.Text, nullable=False)
    subject_kind: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="own", server_default="own"
    )
    vendor: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="mock", server_default="mock"
    )
    trigger: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="manual", server_default="manual"
    )

    status: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="queued", server_default="queued"
    )
    attempts: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0, server_default="0")
    error: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    claimed_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)

    coverage_status: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    # Whether this import may support an ABSENCE claim. False on any truncated,
    # failed, or suspiciously-shrunken pull — such an import records what it saw
    # and mints zero losses.
    measurable: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, default=False, server_default=sa.false()
    )
    # Marks an import whose apparent churn comes from a plan-cap or vendor
    # change rather than the web. Its deltas are recorded but excluded from
    # velocity, so an upgrade does not read as a link explosion.
    retention_boundary: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, default=False, server_default=sa.false()
    )
    rows_ingested: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, default=0, server_default="0"
    )
    reported_total_backlinks: Mapped[int | None] = mapped_column(sa.Integer, nullable=True)
    reported_total_referring_domains: Mapped[int | None] = mapped_column(sa.Integer, nullable=True)
    cost_usd: Mapped[Decimal] = mapped_column(
        sa.Numeric(10, 6), nullable=False, default=0, server_default="0"
    )

    snapshot_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)
    new_in_period: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, default=0, server_default="0"
    )
    lost_in_period: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, default=0, server_default="0"
    )
    yanki_authority: Mapped[int | None] = mapped_column(sa.Integer, nullable=True)
    authority_version: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    # JSON because the decomposition is a publish-only bag read whole for the
    # methodology panel and never filtered on; a column per sub-score would
    # freeze the formula into DDL and block additive versioning.
    authority_components: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    totals: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    provenance: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )


class Backlink(Base):
    """The current belief about one link to the project's own domain.

    Identity is ``(project, vendor, source key, target key)``. ``vendor`` is in
    the key on purpose: after a vendor switch, one index's set must never be
    diffed against another's, which would report the entire profile as lost and
    reborn. The keys are canonicalized (``normalize.url_key``) so cosmetic URL
    churn cannot fork one link into a phantom new+lost pair.

    Competitors are stored rollup-only — see ``ReferringDomainRollup`` — because
    gap analysis needs their referring domains, not their individual links, and
    storing the links would multiply the row count by the competitor count.
    """

    __tablename__ = "backlinks"
    __table_args__ = (
        sa.UniqueConstraint(
            "project_id",
            "vendor",
            "source_url_key",
            "target_url_key",
            name="uq_backlinks_identity",
        ),
        sa.Index("ix_backlinks_project_status", "project_id", "status"),
        sa.Index("ix_backlinks_source_domain", "project_id", "source_domain"),
        sa.CheckConstraint("consecutive_misses >= 0", name="ck_backlinks_misses"),
        sa.CheckConstraint(
            "toxicity_score IS NULL OR toxicity_score BETWEEN 0 AND 100",
            name="ck_backlinks_toxicity",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    org_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    subject_domain: Mapped[str] = mapped_column(sa.Text, nullable=False)
    vendor: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="mock", server_default="mock"
    )

    source_url: Mapped[str] = mapped_column(sa.Text, nullable=False)
    source_url_key: Mapped[str] = mapped_column(sa.Text, nullable=False)
    source_domain: Mapped[str] = mapped_column(sa.Text, nullable=False)
    target_url: Mapped[str] = mapped_column(sa.Text, nullable=False)
    target_url_key: Mapped[str] = mapped_column(sa.Text, nullable=False)

    anchor: Mapped[str] = mapped_column(sa.Text, nullable=False, server_default="")
    anchor_class: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="generic", server_default="generic"
    )
    is_follow: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, default=True, server_default=sa.true()
    )
    is_image_link: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, default=False, server_default=sa.false()
    )
    tld: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    attrs: Mapped[list[Any]] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=False, default=list
    )
    vendor_metrics: Mapped[dict[str, Any]] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=False, default=dict
    )

    # 'active' | 'missing_pending' (seen absent, not yet believed gone) |
    # 'lost' (absence confirmed) | 'lost_unverified' (absence repeated but the
    # verifier could not reach the page — reported as such, never as 'lost').
    status: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="active", server_default="active"
    )
    # The VENDOR's first-seen, not ours. Birth is a fact about the web, not
    # about when our table happened to learn it.
    first_seen_at: Mapped[datetime] = mapped_column(sa.DateTime(timezone=True), nullable=False)
    last_seen_at: Mapped[datetime] = mapped_column(sa.DateTime(timezone=True), nullable=False)
    last_import_id: Mapped[uuid.UUID | None] = mapped_column(sa.Uuid, nullable=True)
    consecutive_misses: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, default=0, server_default="0"
    )
    lost_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)
    lost_reason: Mapped[str | None] = mapped_column(sa.Text, nullable=True)

    verified_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)
    verify_verdict: Mapped[str | None] = mapped_column(sa.Text, nullable=True)

    source_domain_authority: Mapped[float | None] = mapped_column(sa.Float, nullable=True)
    source_page_authority: Mapped[float | None] = mapped_column(sa.Float, nullable=True)
    vendor_spam_score: Mapped[float | None] = mapped_column(sa.Float, nullable=True)
    toxicity_score: Mapped[int | None] = mapped_column(sa.Integer, nullable=True)
    toxicity_band: Mapped[str | None] = mapped_column(sa.Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )


class LinkEvent(Base):
    """Append-only log of what changed: new, lost, regained, changed.

    The evidence behind every delta the product claims. Denormalized (keys,
    domain, urls) so an event stays readable after its ``Backlink`` row is
    pruned by a plan cap — the history must not depend on the inventory.
    """

    __tablename__ = "link_events"
    __table_args__ = (
        sa.Index("ix_link_events_stream", "project_id", "kind", "occurred_at"),
        sa.Index("ix_link_events_at", "project_id", "occurred_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    org_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    backlink_id: Mapped[uuid.UUID | None] = mapped_column(sa.Uuid, nullable=True)
    import_id: Mapped[uuid.UUID | None] = mapped_column(sa.Uuid, nullable=True)
    subject_domain: Mapped[str] = mapped_column(sa.Text, nullable=False)
    vendor: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="mock", server_default="mock"
    )
    source_url_key: Mapped[str] = mapped_column(sa.Text, nullable=False)
    target_url_key: Mapped[str] = mapped_column(sa.Text, nullable=False)
    source_domain: Mapped[str] = mapped_column(sa.Text, nullable=False)
    source_url: Mapped[str] = mapped_column(sa.Text, nullable=False)
    target_url: Mapped[str] = mapped_column(sa.Text, nullable=False)
    kind: Mapped[str] = mapped_column(sa.Text, nullable=False)
    reason: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    detected_by: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="vendor", server_default="vendor"
    )
    verified: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, default=False, server_default=sa.false()
    )
    detail: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    authority_at_event: Mapped[float | None] = mapped_column(sa.Float, nullable=True)
    occurred_at: Mapped[datetime] = mapped_column(sa.DateTime(timezone=True), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )


class ReferringDomainRollup(Base):
    """Per (project, subject, referring domain) current state.

    Three jobs at once, which is why it is one table and not three: the
    gap-analysis substrate, the home of domain-grain toxicity (inlined rather
    than a separate assessments table — the score is a pure function of the
    import and is recomputed with it), and the LINK half of the link-meets-
    citation view whose CITATION half is overlaid on read so it is never stale.

    Competitor profiles live ONLY here.
    """

    __tablename__ = "referring_domain_rollups"
    __table_args__ = (
        sa.UniqueConstraint(
            "project_id",
            "subject_domain",
            "referring_domain",
            name="uq_rd_rollups_domain",
        ),
        sa.Index("ix_rd_rollups_gap", "project_id", "subject_kind", "referring_domain"),
        sa.Index("ix_rd_rollups_toxicity", "project_id", "subject_domain", "toxicity_band"),
        sa.CheckConstraint(
            "toxicity_score IS NULL OR toxicity_score BETWEEN 0 AND 100",
            name="ck_rd_rollups_toxicity",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    org_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    subject_domain: Mapped[str] = mapped_column(sa.Text, nullable=False)
    subject_kind: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="own", server_default="own"
    )
    referring_domain: Mapped[str] = mapped_column(sa.Text, nullable=False)

    links_count: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, default=0, server_default="0"
    )
    follow_links: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, default=0, server_default="0"
    )
    first_linked_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True), nullable=True
    )
    last_linked_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True), nullable=True
    )
    domain_authority: Mapped[float | None] = mapped_column(sa.Float, nullable=True)
    source_subnet: Mapped[str | None] = mapped_column(sa.Text, nullable=True)

    toxicity_score: Mapped[int | None] = mapped_column(sa.Integer, nullable=True)
    toxicity_band: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    toxicity_version: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    # JSON because it is a variable-length list of {code,label,weight,evidence}
    # rendered verbatim so every flag decomposes into its reasons. The BAND is
    # the queryable field; an individual reason never is.
    toxicity_reasons: Mapped[list[Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )

    last_import_id: Mapped[uuid.UUID | None] = mapped_column(sa.Uuid, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )


class AuditEvent(Base):
    """Append-only record of everything that changed, and who changed it (P7.3).

    Append-only is the whole point: no service writes an UPDATE or DELETE here,
    and no code path exposes one. An audit log that can be edited answers a
    weaker question than the one it exists to answer.

    Recorded per event: the actor (a user, an API key, a job, or ``system``),
    the org and entity it touched, the action as a ``resource:action`` string,
    the **before/after values with secrets redacted**, a salted ip hash reusing
    the existing rate-limit salt, and the outcome — including ``denied``,
    because a refused attempt is often the interesting one.

    ``org_id`` is nullable, and that is not an oversight: the anonymous public
    surface produces real, auditable events (a checker submit, a waitlist
    signup) that belong to no tenant. The same NULL-is-public convention as
    ``analyses`` (ADR-35).
    """

    __tablename__ = "audit_events"
    __table_args__ = (
        sa.Index("ix_audit_events_org_occurred", "org_id", "occurred_at"),
        sa.Index("ix_audit_events_entity", "entity_type", "entity_id"),
        sa.Index("ix_audit_events_actor", "actor_type", "actor_id"),
        sa.Index("ix_audit_events_action", "action", "occurred_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    occurred_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    # No FK: an audit event must outlive the organization it describes. A row
    # that disappears when the thing it audits is deleted is not an audit trail.
    org_id: Mapped[uuid.UUID | None] = mapped_column(sa.Uuid, nullable=True)
    workspace_id: Mapped[uuid.UUID | None] = mapped_column(sa.Uuid, nullable=True)

    # 'user' | 'api_key' | 'job' | 'system' | 'anonymous'
    actor_type: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="system", server_default="system"
    )
    actor_id: Mapped[uuid.UUID | None] = mapped_column(sa.Uuid, nullable=True)
    actor_label: Mapped[str | None] = mapped_column(sa.Text, nullable=True)

    action: Mapped[str] = mapped_column(sa.Text, nullable=False)
    entity_type: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    entity_id: Mapped[uuid.UUID | None] = mapped_column(sa.Uuid, nullable=True)

    before: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    after: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )

    ip_hash: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    user_agent: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    request_id: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    # 'success' | 'denied' | 'error'
    outcome: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="success", server_default="success"
    )
    detail: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )

    # Tamper EVIDENCE, on top of the append-only discipline above. A SHA-256 over
    # this row's own content, computed at insert. Editing any audited field
    # without recomputing this — which is what an editor with SQL access does —
    # makes the row fail :func:`app.services.audit.verify_row`, and the admin
    # integrity check reports it.
    #
    # Deliberately a self-hash rather than a chain. A chain (each row hashing its
    # predecessor) also detects deletion, but computing it requires reading and
    # locking the chain head on every write, which would serialize every audited
    # request in the application behind one row. Deletion is instead blocked at
    # the database: migration 0018 installs TWO triggers, one raising on UPDATE
    # or DELETE and a separate statement-level one raising on TRUNCATE — a
    # row-level trigger does not fire on TRUNCATE, so without the second, one
    # word would have erased the whole trail using the app's own role.
    #
    # What remains undetectable is a superuser who drops the triggers first;
    # that is the honest limit of this design, and closing it is the M8
    # hardening card (external append-only sink), not a promise made here.
    #
    # Nullable because the rows written before this column existed cannot be
    # given a credible hash after the fact. The verifier reports those as
    # 'unverifiable' rather than pretending they passed.
    record_hash: Mapped[str | None] = mapped_column(sa.Text, nullable=True)


class Plan(Base):
    """A plan and its limits, as DATA rather than code (P7.6).

    The baseline's tiers (Free/Starter/Pro/Business/Enterprise) are seeded rows,
    not constants, because pricing changes far more often than schema should.
    ``limits`` is JSON for the same reason: every new metered thing (backlink
    rows at M2, keyword slots at M6) would otherwise be a migration and a deploy
    ordering problem.
    """

    __tablename__ = "plans"

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    key: Mapped[str] = mapped_column(sa.Text, nullable=False, unique=True)
    name: Mapped[str] = mapped_column(sa.Text, nullable=False)
    limits: Mapped[dict[str, Any]] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=False, default=dict
    )
    monthly_price_usd: Mapped[Decimal] = mapped_column(
        sa.Numeric(10, 2), nullable=False, default=0, server_default="0"
    )
    active: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, default=True, server_default=sa.true()
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )


class Subscription(Base):
    """Which plan an organization is on. Stripe fills in later (P7.6b).

    Deliberately thin: this card needs "what may this org do" to have an answer,
    not a billing lifecycle. The Stripe columns exist so adding the lifecycle is
    an UPDATE rather than a migration on a populated table.
    """

    __tablename__ = "subscriptions"
    __table_args__ = (
        sa.Index(
            "uq_subscriptions_one_active_per_org",
            "org_id",
            unique=True,
            postgresql_where=sa.text("status IN ('trialing', 'active', 'past_due')"),
            sqlite_where=sa.text("status IN ('trialing', 'active', 'past_due')"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    org_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    plan_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("plans.id", ondelete="RESTRICT"), nullable=False
    )
    status: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="active", server_default="active"
    )
    stripe_customer_id: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    stripe_subscription_id: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    current_period_end: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )


class CreditLedgerEntry(Base):
    """Append-only money movement, per org. The one place spend is true.

    Append-only and signed: a grant is positive, a charge negative, and the
    balance is their sum. Nothing updates a row — correcting a mistake means
    writing its reversal, which leaves both the error and the correction
    visible. A mutable balance column would be faster and would also be the
    number nobody could ever reconcile.

    ``balance_after`` is stored anyway, as a running check: if it ever disagrees
    with the sum of deltas, something wrote out of order and the ledger says so
    rather than quietly drifting.
    """

    __tablename__ = "credit_ledger"
    __table_args__ = (
        sa.Index("ix_credit_ledger_org_created", "org_id", "created_at"),
        sa.Index("ix_credit_ledger_reason", "org_id", "reason"),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    org_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    # Signed: + grant, − charge.
    delta_usd: Mapped[Decimal] = mapped_column(sa.Numeric(12, 6), nullable=False)
    balance_after_usd: Mapped[Decimal] = mapped_column(sa.Numeric(12, 6), nullable=False)
    reason: Mapped[str] = mapped_column(sa.Text, nullable=False)
    # What incurred it — 'analysis', 'backlink_import', 'site_audit', 'grant'.
    source_type: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    source_id: Mapped[uuid.UUID | None] = mapped_column(sa.Uuid, nullable=True)
    actor_id: Mapped[uuid.UUID | None] = mapped_column(sa.Uuid, nullable=True)
    detail: Mapped[dict[str, Any] | None] = mapped_column(
        sa.JSON().with_variant(JSONB, "postgresql"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow
    )


class UsageCounter(Base):
    """How much of a metered thing an org has used in one window.

    Separate from the ledger because they answer different questions: the ledger
    is money and is kept forever; this is "have you hit your limit this month"
    and is a small, updatable counter. Conflating them would make either the
    money mutable or the quota check a sum over history.
    """

    __tablename__ = "usage_counters"
    __table_args__ = (
        sa.UniqueConstraint("org_id", "metric", "window_start", name="uq_usage_counters_window"),
        sa.Index("ix_usage_counters_org_metric", "org_id", "metric"),
    )

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    org_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    metric: Mapped[str] = mapped_column(sa.Text, nullable=False)
    window_start: Mapped[datetime] = mapped_column(sa.DateTime(timezone=True), nullable=False)
    used: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0, server_default="0")
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )
