"""backlink intelligence schema v1 (Phase 8 / P8.1)

Revision ID: 0013_backlinks
Revises: 0012_tenancy
Create Date: 2026-08-05

Five new tables, all org-scoped from birth because the tenancy seam (0012)
already existed when they were written — which is the entire argument for having
done the Admin Platform first. Nothing existing is altered, so this migration
cannot affect a single live code path: the module ships behind
``BACKLINKS_ENABLED`` (default off) and has no vendor until operator item A4.

Autogenerated from the models and then read line by line, which is only safe
because session 21 fixed the eight-index model/migration drift first — before
that fix, autogenerate would have proposed dropping production indexes.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0013_backlinks"
down_revision = "0012_tenancy"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backlink_competitors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("competitor_domain", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("tracked_since", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "competitor_domain", name="uq_backlink_competitors"),
    )
    op.create_index(
        op.f("ix_backlink_competitors_org_id"), "backlink_competitors", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_backlink_competitors_project_id"),
        "backlink_competitors",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "backlink_imports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("subject_domain", sa.Text(), nullable=False),
        sa.Column("subject_kind", sa.Text(), server_default="own", nullable=False),
        sa.Column("vendor", sa.Text(), server_default="mock", nullable=False),
        sa.Column("trigger", sa.Text(), server_default="manual", nullable=False),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("coverage_status", sa.Text(), nullable=True),
        sa.Column("measurable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "retention_boundary", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("rows_ingested", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reported_total_backlinks", sa.Integer(), nullable=True),
        sa.Column("reported_total_referring_domains", sa.Integer(), nullable=True),
        sa.Column(
            "cost_usd", sa.Numeric(precision=10, scale=6), server_default="0", nullable=False
        ),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("new_in_period", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lost_in_period", sa.Integer(), server_default="0", nullable=False),
        sa.Column("yanki_authority", sa.Integer(), nullable=True),
        sa.Column("authority_version", sa.Text(), nullable=True),
        sa.Column(
            "authority_components",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "totals",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("attempts >= 0", name="ck_backlink_imports_attempts"),
        sa.CheckConstraint(
            "yanki_authority IS NULL OR yanki_authority BETWEEN 0 AND 100",
            name="ck_backlink_imports_authority",
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_backlink_imports_org_id"), "backlink_imports", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_backlink_imports_project_id"), "backlink_imports", ["project_id"], unique=False
    )
    op.create_index(
        "ix_backlink_imports_queue",
        "backlink_imports",
        ["status", "claimed_at", "created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
        sqlite_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index(
        "ix_backlink_imports_series",
        "backlink_imports",
        ["project_id", "subject_domain", "snapshot_at"],
        unique=False,
    )
    op.create_index(
        "uq_backlink_imports_one_active",
        "backlink_imports",
        ["project_id", "subject_domain"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
        sqlite_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_table(
        "backlinks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("subject_domain", sa.Text(), nullable=False),
        sa.Column("vendor", sa.Text(), server_default="mock", nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_url_key", sa.Text(), nullable=False),
        sa.Column("source_domain", sa.Text(), nullable=False),
        sa.Column("target_url", sa.Text(), nullable=False),
        sa.Column("target_url_key", sa.Text(), nullable=False),
        sa.Column("anchor", sa.Text(), server_default="", nullable=False),
        sa.Column("anchor_class", sa.Text(), server_default="generic", nullable=False),
        sa.Column("is_follow", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_image_link", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("tld", sa.Text(), nullable=True),
        sa.Column(
            "attrs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "vendor_metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_import_id", sa.Uuid(), nullable=True),
        sa.Column("consecutive_misses", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lost_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lost_reason", sa.Text(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verify_verdict", sa.Text(), nullable=True),
        sa.Column("source_domain_authority", sa.Float(), nullable=True),
        sa.Column("source_page_authority", sa.Float(), nullable=True),
        sa.Column("vendor_spam_score", sa.Float(), nullable=True),
        sa.Column("toxicity_score", sa.Integer(), nullable=True),
        sa.Column("toxicity_band", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("consecutive_misses >= 0", name="ck_backlinks_misses"),
        sa.CheckConstraint(
            "toxicity_score IS NULL OR toxicity_score BETWEEN 0 AND 100",
            name="ck_backlinks_toxicity",
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "vendor", "source_url_key", "target_url_key", name="uq_backlinks_identity"
        ),
    )
    op.create_index(op.f("ix_backlinks_org_id"), "backlinks", ["org_id"], unique=False)
    op.create_index(op.f("ix_backlinks_project_id"), "backlinks", ["project_id"], unique=False)
    op.create_index(
        "ix_backlinks_project_status", "backlinks", ["project_id", "status"], unique=False
    )
    op.create_index(
        "ix_backlinks_source_domain", "backlinks", ["project_id", "source_domain"], unique=False
    )
    op.create_table(
        "link_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("backlink_id", sa.Uuid(), nullable=True),
        sa.Column("import_id", sa.Uuid(), nullable=True),
        sa.Column("subject_domain", sa.Text(), nullable=False),
        sa.Column("vendor", sa.Text(), server_default="mock", nullable=False),
        sa.Column("source_url_key", sa.Text(), nullable=False),
        sa.Column("target_url_key", sa.Text(), nullable=False),
        sa.Column("source_domain", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("target_url", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("detected_by", sa.Text(), server_default="vendor", nullable=False),
        sa.Column("verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("authority_at_event", sa.Float(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_link_events_at", "link_events", ["project_id", "occurred_at"], unique=False)
    op.create_index(op.f("ix_link_events_org_id"), "link_events", ["org_id"], unique=False)
    op.create_index(op.f("ix_link_events_project_id"), "link_events", ["project_id"], unique=False)
    op.create_index(
        "ix_link_events_stream", "link_events", ["project_id", "kind", "occurred_at"], unique=False
    )
    op.create_table(
        "referring_domain_rollups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("subject_domain", sa.Text(), nullable=False),
        sa.Column("subject_kind", sa.Text(), server_default="own", nullable=False),
        sa.Column("referring_domain", sa.Text(), nullable=False),
        sa.Column("links_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("follow_links", sa.Integer(), server_default="0", nullable=False),
        sa.Column("first_linked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_linked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("domain_authority", sa.Float(), nullable=True),
        sa.Column("source_subnet", sa.Text(), nullable=True),
        sa.Column("toxicity_score", sa.Integer(), nullable=True),
        sa.Column("toxicity_band", sa.Text(), nullable=True),
        sa.Column("toxicity_version", sa.Text(), nullable=True),
        sa.Column(
            "toxicity_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("last_import_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "toxicity_score IS NULL OR toxicity_score BETWEEN 0 AND 100",
            name="ck_rd_rollups_toxicity",
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "subject_domain", "referring_domain", name="uq_rd_rollups_domain"
        ),
    )
    op.create_index(
        "ix_rd_rollups_gap",
        "referring_domain_rollups",
        ["project_id", "subject_kind", "referring_domain"],
        unique=False,
    )
    op.create_index(
        "ix_rd_rollups_toxicity",
        "referring_domain_rollups",
        ["project_id", "subject_domain", "toxicity_band"],
        unique=False,
    )
    op.create_index(
        op.f("ix_referring_domain_rollups_org_id"),
        "referring_domain_rollups",
        ["org_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_referring_domain_rollups_project_id"),
        "referring_domain_rollups",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_referring_domain_rollups_project_id"), table_name="referring_domain_rollups"
    )
    op.drop_index(op.f("ix_referring_domain_rollups_org_id"), table_name="referring_domain_rollups")
    op.drop_index("ix_rd_rollups_toxicity", table_name="referring_domain_rollups")
    op.drop_index("ix_rd_rollups_gap", table_name="referring_domain_rollups")
    op.drop_table("referring_domain_rollups")
    op.drop_index("ix_link_events_stream", table_name="link_events")
    op.drop_index(op.f("ix_link_events_project_id"), table_name="link_events")
    op.drop_index(op.f("ix_link_events_org_id"), table_name="link_events")
    op.drop_index("ix_link_events_at", table_name="link_events")
    op.drop_table("link_events")
    op.drop_index("ix_backlinks_source_domain", table_name="backlinks")
    op.drop_index("ix_backlinks_project_status", table_name="backlinks")
    op.drop_index(op.f("ix_backlinks_project_id"), table_name="backlinks")
    op.drop_index(op.f("ix_backlinks_org_id"), table_name="backlinks")
    op.drop_table("backlinks")
    op.drop_index(
        "uq_backlink_imports_one_active",
        table_name="backlink_imports",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
        sqlite_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index("ix_backlink_imports_series", table_name="backlink_imports")
    op.drop_index(
        "ix_backlink_imports_queue",
        table_name="backlink_imports",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
        sqlite_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index(op.f("ix_backlink_imports_project_id"), table_name="backlink_imports")
    op.drop_index(op.f("ix_backlink_imports_org_id"), table_name="backlink_imports")
    op.drop_table("backlink_imports")
    op.drop_index(op.f("ix_backlink_competitors_project_id"), table_name="backlink_competitors")
    op.drop_index(op.f("ix_backlink_competitors_org_id"), table_name="backlink_competitors")
    op.drop_table("backlink_competitors")
    # ### end Alembic commands ###
