"""plans, subscriptions, credit ledger, usage counters (Phase 7 / P7.6)

Revision ID: 0015_billing
Revises: 0014_audit_events
Create Date: 2026-08-05

Four additive tables, no existing table altered. The plan catalog is DATA, not
constants — pricing changes far more often than schema should — and `limits` is
JSON so a new metered thing (backlink rows at M2, keyword slots at M6) needs no
migration.

The ledger is append-only and signed. `balance_after_usd` is stored as a running
check rather than as the source of truth: if it ever disagrees with the sum of
deltas, something wrote out of order and the ledger can say so instead of
drifting quietly.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0015_billing"
down_revision = "0014_audit_events"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "limits",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "monthly_price_usd",
            sa.Numeric(precision=10, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "credit_ledger",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("delta_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("balance_after_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_credit_ledger_org_created", "credit_ledger", ["org_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_credit_ledger_org_id"), "credit_ledger", ["org_id"], unique=False)
    op.create_index("ix_credit_ledger_reason", "credit_ledger", ["org_id", "reason"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("stripe_customer_id", sa.Text(), nullable=True),
        sa.Column("stripe_subscription_id", sa.Text(), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscriptions_org_id"), "subscriptions", ["org_id"], unique=False)
    op.create_index(
        "uq_subscriptions_one_active_per_org",
        "subscriptions",
        ["org_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('trialing', 'active', 'past_due')"),
        sqlite_where=sa.text("status IN ('trialing', 'active', 'past_due')"),
    )
    op.create_table(
        "usage_counters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "metric", "window_start", name="uq_usage_counters_window"),
    )
    op.create_index(op.f("ix_usage_counters_org_id"), "usage_counters", ["org_id"], unique=False)
    op.create_index(
        "ix_usage_counters_org_metric", "usage_counters", ["org_id", "metric"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_counters_org_metric", table_name="usage_counters")
    op.drop_index(op.f("ix_usage_counters_org_id"), table_name="usage_counters")
    op.drop_table("usage_counters")
    op.drop_index(
        "uq_subscriptions_one_active_per_org",
        table_name="subscriptions",
        postgresql_where=sa.text("status IN ('trialing', 'active', 'past_due')"),
        sqlite_where=sa.text("status IN ('trialing', 'active', 'past_due')"),
    )
    op.drop_index(op.f("ix_subscriptions_org_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index("ix_credit_ledger_reason", table_name="credit_ledger")
    op.drop_index(op.f("ix_credit_ledger_org_id"), table_name="credit_ledger")
    op.drop_index("ix_credit_ledger_org_created", table_name="credit_ledger")
    op.drop_table("credit_ledger")
    op.drop_table("plans")
    # ### end Alembic commands ###
