"""users.status and users.last_active_at (account enable/disable)

Revision ID: 0017_user_status
Revises: 0016_seed_plans
Create Date: 2026-08-05

Two nullable-or-defaulted columns on a table with three rows. Additive.

`status` is what an administrator's enable/disable switch writes. Disabling is
deliberately NOT deleting: the history, the audit trail and the org membership
all survive, and re-enabling restores access rather than recreating a person.
Existing rows default to 'active', so the deploy changes nobody's access.
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0017_user_status"
down_revision = "0016_seed_plans"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("status", sa.Text(), server_default="active", nullable=False))
    op.add_column("users", sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_active_at")
    op.drop_column("users", "status")
    # ### end Alembic commands ###
