"""Google Search Console foundation: connections, oauth states, project links

Revision ID: 0019_google_search_console
Revises: 0018_invitations_audit_integrity
Create Date: 2026-08-06

Three new tables and nothing else. No existing table is altered, no data is
backfilled, and no code path reads any of this yet: the module ships behind
``GSC_ENABLED`` (default off) and this slice adds no routes, no worker and no
Google client library. That makes the migration unable to affect a live request
in either direction, which is the property that lets the schema land before the
feature does.

Identity is ``(org_id, google_account_id)`` on ``google_connections``, not
``org_id`` alone — an agency holds several Google accounts and must not have to
disconnect one client to look at another. ``site_audit_search_console_links``
inverts that: ``seo_project_id`` is unique so a project has exactly one
property, while ``google_connection_id`` is not, so one account serves many
projects.

``google_oauth_states`` stores SHA-256 of both the state and the OIDC nonce,
never the raw values, and ``consumed_at`` makes a state single-use — the pair is
what stops a replayed callback. The nonce is a separate column because it
answers a separate question: state proves the callback answers a request we
made, the nonce proves the ID token inside it was minted for *this* attempt. Its
index is partial on ``consumed_at IS NULL`` because a consumed row is never read
again.

Written by hand in the explicit style of 0009/0012 rather than autogenerated, so
the constraint and index names are the ones the models declare.
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0019_google_search_console"
down_revision = "0018_invitations_audit_integrity"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "google_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("google_account_id", sa.Text(), nullable=False),
        sa.Column("google_account_email", sa.Text(), nullable=False),
        sa.Column("scopes", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("refresh_token_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("encryption_key_version", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("connected_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["connected_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "org_id",
            "google_account_id",
            name="uq_google_connections_org_account",
        ),
    )
    op.create_index("ix_google_connections_org_id", "google_connections", ["org_id"])

    op.create_table(
        "google_oauth_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("state_hash", sa.Text(), nullable=False),
        sa.Column("nonce_hash", sa.Text(), nullable=False),
        sa.Column("code_verifier", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("seo_project_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["seo_project_id"], ["seo_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_hash", name="uq_google_oauth_states_state_hash"),
    )
    op.create_index(
        "ix_google_oauth_states_pending",
        "google_oauth_states",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("consumed_at IS NULL"),
        sqlite_where=sa.text("consumed_at IS NULL"),
    )

    op.create_table(
        "site_audit_search_console_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seo_project_id", sa.Uuid(), nullable=False),
        sa.Column("google_connection_id", sa.Uuid(), nullable=False),
        sa.Column("site_url", sa.Text(), nullable=False),
        sa.Column("property_type", sa.Text(), nullable=False),
        sa.Column("permission_level", sa.Text(), nullable=False),
        sa.Column("connected_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["seo_project_id"], ["seo_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["google_connection_id"], ["google_connections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["connected_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "seo_project_id",
            name="uq_site_audit_search_console_links_project",
        ),
    )
    op.create_index(
        "ix_site_audit_search_console_links_connection",
        "site_audit_search_console_links",
        ["google_connection_id"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_site_audit_search_console_links_connection",
        table_name="site_audit_search_console_links",
    )
    op.drop_table("site_audit_search_console_links")

    op.drop_index(
        "ix_google_oauth_states_pending",
        table_name="google_oauth_states",
        postgresql_where=sa.text("consumed_at IS NULL"),
        sqlite_where=sa.text("consumed_at IS NULL"),
    )
    op.drop_table("google_oauth_states")

    op.drop_index("ix_google_connections_org_id", table_name="google_connections")
    op.drop_table("google_connections")
