"""analyses.created_by_user_id — attribute GEO runs to the submitting user

Revision ID: 0019_analysis_created_by_user
Revises: 0018_invitations_audit_integrity
Create Date: 2026-08-17

Autogenerated from ``app.db.models.Analysis`` (``alembic revision --autogenerate``).
Nullable additive column. Existing rows stay NULL (legacy / anonymous scope).
No FK yet — same deferral as analyses.org_id (ADR-35).
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision = "0019_analysis_created_by_user"
down_revision = "0018_invitations_audit_integrity"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analyses", sa.Column("created_by_user_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_analyses_created_by_user_id",
        "analyses",
        ["created_by_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_analyses_created_by_user_id", table_name="analyses")
    op.drop_column("analyses", "created_by_user_id")
    # ### end Alembic commands ###
