"""users.auth_provider / auth_subject, and a password that may be absent

Revision ID: 0020_oauth_identity
Revises: 0019_analysis_created_by_user
Create Date: 2026-08-18

Autogenerated from ``app.db.models.User`` (``alembic revision --autogenerate``).
Additive columns, plus one constraint relaxation: ``password_hash`` becomes
nullable because an account created through Google or Apple has no password to
hash. Relaxing a NOT NULL never invalidates an existing row.

``auth_subject`` is the provider's immutable id for the account; matching on the
email alone would lose the user the day they change it at the provider. The pair
is unique, and NULLs are exempt from that constraint in Postgres, which keeps
every password account out of its way.

The downgrade re-imposes NOT NULL, so it fails while a passwordless account
exists — the honest failure, since there is no password to invent for those rows.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0020_oauth_identity"
down_revision: str | None = "0019_analysis_created_by_user"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("auth_provider", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("auth_subject", sa.Text(), nullable=True))
    op.alter_column("users", "password_hash", existing_type=sa.TEXT(), nullable=True)
    op.create_unique_constraint(
        "uq_users_auth_provider_subject", "users", ["auth_provider", "auth_subject"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_auth_provider_subject", "users", type_="unique")
    op.alter_column("users", "password_hash", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("users", "auth_subject")
    op.drop_column("users", "auth_provider")
    # ### end Alembic commands ###
