"""add analysis kyc cost fields

Revision ID: 0023_analysis_kyc_cost
Revises: 0022_prompt_provenance
Create Date: 2026-08-20 13:53:28.948015
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0023_analysis_kyc_cost"
down_revision: str | None = "0022_prompt_provenance"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyses",
        sa.Column(
            "kyc_cost_usd", sa.Numeric(precision=10, scale=6), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "analyses",
        sa.Column(
            "kyc_usage",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyses", "kyc_usage")
    op.drop_column("analyses", "kyc_cost_usd")
    # ### end Alembic commands ###
