"""GEO run metadata + response llm_provider rename (ADR-51)

Revision ID: 0024_geo_run_metadata
Revises: 0023_analysis_kyc_cost
Create Date: 2026-09-09

Autogenerated from ``app.db.models`` (``alembic revision --autogenerate``),
with one hand edit: ``responses.engine`` is renamed to ``llm_provider`` rather
than dropped and re-added, so existing rows survive the upgrade.

Schema-only. Legacy value repair (``measured`` / ``simulated`` mode slugs →
``openrouter`` + ``analyses.geo_run``) lives in ``0025_backfill_geo_run``.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0024_geo_run_metadata"
down_revision: str | None = "0023_analysis_kyc_cost"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_JSON = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_cache")
    op.add_column("analyses", sa.Column("geo_run", _JSON, nullable=True))
    op.drop_column("geo_records", "measurement_mode")
    op.drop_column("geo_records", "model")
    op.drop_column("geo_records", "search_provider")
    op.alter_column("responses", "engine", new_column_name="llm_provider")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("responses", "llm_provider", new_column_name="engine")
    op.add_column("geo_records", sa.Column("search_provider", sa.Text(), nullable=True))
    op.add_column("geo_records", sa.Column("model", sa.Text(), nullable=True))
    op.add_column("geo_records", sa.Column("measurement_mode", sa.Text(), nullable=True))
    op.drop_column("analyses", "geo_run")
    op.create_table(
        "llm_cache",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cache_key", sa.Text(), nullable=False),
        sa.Column("engine", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=False),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=10, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cache_key"),
    )
    # ### end Alembic commands ###
