"""geo sector key

Revision ID: 0026
Revises: 0025_backfill_geo_run
Create Date: 2026-09-21 11:53:52.873795
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0026"
down_revision: str | None = "0025_backfill_geo_run"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("geo_records", sa.Column("sector_key", sa.Text(), nullable=True))
    op.create_index(op.f("ix_geo_records_sector_key"), "geo_records", ["sector_key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geo_records_sector_key"), table_name="geo_records")
    op.drop_column("geo_records", "sector_key")
    # ### end Alembic commands ###
