"""brand_contexts table + analyses.brand_context_id (ADR-52, mod-1)

Revision ID: 0026_brand_contexts
Revises: 0025_backfill_geo_run
Create Date: 2026-09-19

Autogenerated from ``app.db.models`` (``alembic revision --autogenerate``),
with one hand edit: named FK ``fk_analyses_brand_context_id`` so downgrade is
stable.

Phase A of standalone modules: durable brand profile entity with an optional,
nullable link from analyses. Additive only — no change to the monolith pipeline
write path (``analyses.kyc`` remains until mod-5).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0026_brand_contexts"
down_revision: str | None = "0025_backfill_geo_run"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand_contexts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("brand", sa.Text(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=True),
        sa.Column("locale", sa.Text(), server_default="en", nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column(
            "competitors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "profile",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_brand_contexts_created_by_user_id",
        "brand_contexts",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index("ix_brand_contexts_org_id", "brand_contexts", ["org_id"], unique=False)
    op.add_column("analyses", sa.Column("brand_context_id", sa.Uuid(), nullable=True))
    op.create_index("ix_analyses_brand_context_id", "analyses", ["brand_context_id"], unique=False)
    op.create_foreign_key(
        "fk_analyses_brand_context_id",
        "analyses",
        "brand_contexts",
        ["brand_context_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_analyses_brand_context_id", "analyses", type_="foreignkey")
    op.drop_index("ix_analyses_brand_context_id", table_name="analyses")
    op.drop_column("analyses", "brand_context_id")
    op.drop_index("ix_brand_contexts_org_id", table_name="brand_contexts")
    op.drop_index("ix_brand_contexts_created_by_user_id", table_name="brand_contexts")
    op.drop_table("brand_contexts")
    # ### end Alembic commands ###
