"""module_runs table — standalone worker job queue (mod-6)

Revision ID: 0027_module_runs
Revises: 0026_brand_contexts
Create Date: 2026-09-19

Autogenerated from ``app.db.models`` (``alembic revision --autogenerate``),
with named FKs for stable downgrade.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0027_module_runs"
down_revision: str | None = "0026_brand_contexts"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "module_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("current_step", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("brand_context_id", sa.Uuid(), nullable=True),
        sa.Column("linked_analysis_id", sa.Uuid(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_context_id"],
            ["brand_contexts.id"],
            name="fk_module_runs_brand_context_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["linked_analysis_id"],
            ["analyses.id"],
            name="fk_module_runs_linked_analysis_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_module_runs_brand_context_id",
        "module_runs",
        ["brand_context_id"],
        unique=False,
    )
    op.create_index(
        "ix_module_runs_job_kind_status",
        "module_runs",
        ["job_kind", "status"],
        unique=False,
    )
    op.create_index("ix_module_runs_org_id", "module_runs", ["org_id"], unique=False)
    op.create_index(
        "ix_module_runs_status_created",
        "module_runs",
        ["status", "created_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_module_runs_status_created", table_name="module_runs")
    op.drop_index("ix_module_runs_org_id", table_name="module_runs")
    op.drop_index("ix_module_runs_job_kind_status", table_name="module_runs")
    op.drop_index("ix_module_runs_brand_context_id", table_name="module_runs")
    op.drop_table("module_runs")
