/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Analysis */
        post: operations["submit_analysis_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Analysis */
        get: operations["read_analysis_api_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Validate a user's email and password.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current refresh-token family and clear its cookie.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the user represented by the access bearer token.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate the refresh token and return a new access token.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Create a user account with a hashed password.
         */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Checker */
        post: operations["submit_checker_api_v1_checker_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checker/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Checker Lead */
        post: operations["submit_checker_lead_api_v1_checker_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Waitlist */
        post: operations["join_waitlist_api_v1_waitlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisOut */
        AnalysisOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Step */
            current_step: string | null;
            /** Error */
            error: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Progress */
            progress: number;
            result: components["schemas"]["ResultOut"];
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url: string;
        };
        /** CheckerLeadRequest */
        CheckerLeadRequest: {
            /** Email */
            email: string;
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
        };
        /**
         * CheckerSubmitRequest
         * @description A public checker submit. brand+category must be non-empty after trim.
         */
        CheckerSubmitRequest: {
            /** Brand */
            brand: string;
            /** Category */
            category: string;
            /**
             * Lang
             * @default en
             */
            lang: string;
        };
        /** CheckerSubmitResponse */
        CheckerSubmitResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
        };
        /**
         * CompetitorMention
         * @description A competitor brand that showed up in the answers and how many answers
         *     named it (P5.3) — a proper-noun co-mention over the raw text, not the KYC
         *     competitor list.
         */
        CompetitorMention: {
            /** Mentions */
            mentions: number;
            /** Name */
            name: string;
        };
        /** CreateAnalysisRequest */
        CreateAnalysisRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** CreateAnalysisResponse */
        CreateAnalysisResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * EnginePresence
         * @description One engine's presence in a checker run: ``mentioned`` of ``total`` answers
         *     named the searched brand (P5.3). Read-time aggregate of the ``footprint``
         *     booleans; the per-engine totals sum to ``total_responses``.
         */
        EnginePresence: {
            /** Engine */
            engine: string;
            /** Mentioned */
            mentioned: number;
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description Credentials required to authenticate a user.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description Authenticated user and bearer token returned after login.
         */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            user: components["schemas"]["UserOut"];
        };
        /** PromptOut */
        PromptOut: {
            /** Category */
            category: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text */
            text: string;
        };
        /**
         * RefreshResponse
         * @description New bearer token returned after refresh-token rotation.
         */
        RefreshResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** ResponseOut */
        ResponseOut: {
            /** Cost Usd */
            cost_usd: number;
            /** Engine */
            engine: string;
            /** Footprint */
            footprint: boolean | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Matched Snippet */
            matched_snippet: string | null;
            /** Model */
            model: string;
            /**
             * Prompt Id
             * Format: uuid
             */
            prompt_id: string;
            /** Raw Text */
            raw_text: string;
        };
        /** ResultOut */
        ResultOut: {
            /** Competitors Appeared */
            competitors_appeared: components["schemas"]["CompetitorMention"][] | null;
            /** Engine Presence */
            engine_presence: components["schemas"]["EnginePresence"][] | null;
            /** Footprint Count */
            footprint_count: number | null;
            /** Geo Score */
            geo_score: number | null;
            /** Kyc */
            kyc: {
                [key: string]: unknown;
            } | null;
            /** Prompts */
            prompts: components["schemas"]["PromptOut"][];
            /** Responses */
            responses: components["schemas"]["ResponseOut"][];
            serp: components["schemas"]["SerpVisibilityOut"] | null;
            /** Total Responses */
            total_responses: number | null;
        };
        /**
         * SerpCheckOut
         * @description One search query run for an analysis, and what the results page showed.
         *
         *     ``hit`` is nullable and the distinction matters to anyone reading this: NULL
         *     is a page we could not read (the search instance was unreachable, or every
         *     upstream engine refused it) and is excluded from the score; ``false`` is a
         *     real, counted miss.
         */
        SerpCheckOut: {
            /** Hit */
            hit: boolean | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Matched Snippet */
            matched_snippet: string | null;
            /** Matched Url */
            matched_url: string | null;
            /** Matched Via */
            matched_via: string | null;
            /** Query */
            query: string;
            /** Rank */
            rank: number | null;
            /** Result Count */
            result_count: number;
            /** Source */
            source: string;
            /** Unresponsive Engines */
            unresponsive_engines: string | null;
        };
        /**
         * SerpVisibilityOut
         * @description SERP visibility for one analysis (ADR-28).
         *
         *     Present only on runs where the feature was switched on; ``ResultOut.serp``
         *     stays null otherwise, so "we did not look" is never rendered as a zero.
         *     ``score`` is separately nullable *within* a present summary: that is the run
         *     where we did look and could not read the results.
         */
        SerpVisibilityOut: {
            /** Checks */
            checks: components["schemas"]["SerpCheckOut"][];
            /** Hits */
            hits: number;
            /** Queries */
            queries: number;
            /** Score */
            score: number | null;
            /** Source */
            source: string | null;
            /** Status */
            status: string;
        };
        /**
         * SignupRequest
         * @description Credentials required to create a user account.
         */
        SignupRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserOut
         * @description Public user fields returned by authentication endpoints.
         */
        UserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WaitlistRequest
         * @description A public waitlist signup. The email is validated + normalized server-side
         *     (trim + lowercase) so a malformed address is a 422 before any row is written,
         *     and the stored value matches the unique lowercased column.
         */
        WaitlistRequest: {
            /** Email */
            email: string;
        };
        /** WaitlistResponse */
        WaitlistResponse: {
            /** Ok */
            ok: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submit_analysis_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_analysis_api_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_checker_api_v1_checker_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckerSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckerSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_checker_lead_api_v1_checker_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckerLeadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_waitlist_api_v1_waitlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
