/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Members
         * @description Members of the caller's organization, searchable.
         *
         *     Search is a case-insensitive substring over the email, which is the only
         *     human-readable identifier a user has today. It is applied in SQL rather
         *     than after fetching, so the limit means what it says on a large org.
         */
        get: operations["list_members_api_v1_admin_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Member */
        get: operations["read_member_api_v1_admin_members__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Member
         * @description Change a member's role, or enable/disable their account.
         *
         *     Both guards below prevent the same class of accident — an organization
         *     locking itself out with no way back in except a support ticket.
         */
        patch: operations["update_member_api_v1_admin_members__user_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Organization
         * @description The caller's own organization, with its member count.
         */
        get: operations["read_organization_api_v1_admin_organization_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Analysis */
        post: operations["submit_analysis_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Analysis */
        get: operations["read_analysis_api_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Validate a user's email and password.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current refresh-token family and clear its cookie.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who you are, which organization you are acting in, and what you may do.
         *
         *     The role and permission list ride along so the UI can hide a control the
         *     caller cannot use, instead of showing it and failing on click. They are for
         *     RENDERING ONLY — every endpoint enforces its own permission independently,
         *     so a client that lies about this list gets a 403 exactly as before.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate the refresh token and return a new access token.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Create a user account with a hashed password.
         */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Checker */
        post: operations["submit_checker_api_v1_checker_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checker/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Checker Lead */
        post: operations["submit_checker_lead_api_v1_checker_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seo-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Seo Projects */
        get: operations["read_seo_projects_api_v1_seo_projects_get"];
        put?: never;
        /** Create Seo Project */
        post: operations["create_seo_project_api_v1_seo_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seo-projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Seo Project */
        get: operations["read_seo_project_api_v1_seo_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seo-projects/{project_id}/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Site Audit */
        post: operations["create_site_audit_api_v1_seo_projects__project_id__audits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seo-projects/{project_id}/audits/{audit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Site Audit */
        get: operations["read_site_audit_api_v1_seo_projects__project_id__audits__audit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Waitlist */
        post: operations["join_waitlist_api_v1_waitlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminMemberOut
         * @description One member of an organization, as an administrator sees them.
         */
        AdminMemberOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Active At */
            last_active_at?: string | null;
            /**
             * Membership Id
             * Format: uuid
             */
            membership_id: string;
            /** Membership Status */
            membership_status: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /**
         * AdminMemberUpdateRequest
         * @description Change a member's role, their account status, or both.
         *
         *     Both optional: a PATCH that sets neither is a no-op rather than an error,
         *     which keeps a form that only touched one field simple to submit.
         */
        AdminMemberUpdateRequest: {
            /** Role */
            role?: string | null;
            /** Status */
            status?: string | null;
        };
        /**
         * AdminOrganizationOut
         * @description The caller's organization.
         */
        AdminOrganizationOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Member Count */
            member_count: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
        };
        /**
         * AdminUserListOut
         * @description A page of members, plus what the UI needs to render its controls.
         *
         *     ``assignable_roles`` ships with the list so the role picker is populated
         *     from the server's idea of what may be assigned rather than a hardcoded
         *     frontend copy that drifts. Platform roles are excluded there, so a customer
         *     cannot even be offered one.
         */
        AdminUserListOut: {
            /** Assignable Roles */
            assignable_roles: string[];
            /** Limit */
            limit: number;
            /** Members */
            members: components["schemas"]["AdminMemberOut"][];
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** AnalysisOut */
        AnalysisOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Step */
            current_step: string | null;
            /** Error */
            error: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Progress */
            progress: number;
            result: components["schemas"]["ResultOut"];
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url: string;
        };
        /** CheckerLeadRequest */
        CheckerLeadRequest: {
            /** Email */
            email: string;
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
        };
        /**
         * CheckerSubmitRequest
         * @description A public checker submit. brand+category must be non-empty after trim.
         */
        CheckerSubmitRequest: {
            /** Brand */
            brand: string;
            /** Category */
            category: string;
            /**
             * Lang
             * @default en
             */
            lang: string;
        };
        /** CheckerSubmitResponse */
        CheckerSubmitResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
        };
        /**
         * CompetitorMention
         * @description A competitor brand that showed up in the answers and how many answers
         *     named it (P5.3) — a proper-noun co-mention over the raw text, not the KYC
         *     competitor list.
         */
        CompetitorMention: {
            /** Mentions */
            mentions: number;
            /** Name */
            name: string;
        };
        /** CreateAnalysisRequest */
        CreateAnalysisRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** CreateAnalysisResponse */
        CreateAnalysisResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** CreateSeoProjectRequest */
        CreateSeoProjectRequest: {
            /** Domain */
            domain: string;
            /**
             * Js Rendering
             * @default true
             */
            js_rendering: boolean;
            /** Name */
            name?: string | null;
            /**
             * Page Limit
             * @default 10
             */
            page_limit: number;
            /**
             * Profile Id
             * @default site_audit_mobile
             * @enum {string}
             */
            profile_id: "site_audit_mobile" | "site_audit_desktop";
        };
        /**
         * CurrentUserOut
         * @description ``/auth/me`` — who you are AND what you can do.
         *
         *     The role and permission list ride along so the UI can reflect authority
         *     without a second round trip. They are for RENDERING only: the API enforces
         *     every one of them independently, and a client that lies about its
         *     permissions gets a 403 exactly as before.
         */
        CurrentUserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            organization?: components["schemas"]["OrganizationOut"] | null;
            /** Permissions */
            permissions?: string[];
            /** Role */
            role?: string | null;
            /** Status */
            status: string;
        };
        /**
         * EnginePresence
         * @description One engine's presence in a checker run: ``mentioned`` of ``total`` answers
         *     named the searched brand (P5.3). Read-time aggregate of the ``footprint``
         *     booleans; the per-engine totals sum to ``total_responses``.
         */
        EnginePresence: {
            /** Engine */
            engine: string;
            /** Mentioned */
            mentioned: number;
            /** Total */
            total: number;
        };
        /**
         * GeoRecordOut
         * @description One Kaira-style audit record persisted columnar in ``geo_records``.
         */
        GeoRecordOut: {
            /** Answer Summary */
            answer_summary?: string | null;
            /** Brand */
            brand: string;
            /** Citation Metrics */
            citation_metrics?: {
                [key: string]: unknown;
            } | null;
            /** Citations */
            citations?: unknown[] | null;
            /** Competitors */
            competitors?: unknown[] | null;
            /** Content Improvement Opportunities */
            content_improvement_opportunities?: unknown[] | null;
            /** Entities Associated With Brand */
            entities_associated_with_brand?: unknown[] | null;
            /** Error */
            error?: boolean | null;
            /** Generated At */
            generated_at?: string | null;
            /** Grounded Answer */
            grounded_answer?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Intent */
            intent?: string | null;
            /** Measurement Mode */
            measurement_mode?: string | null;
            /** Mention Context */
            mention_context?: string | null;
            /** Mentioned */
            mentioned?: boolean | null;
            /** Model */
            model?: string | null;
            /** Owned Domains */
            owned_domains?: unknown[] | null;
            /** Prompt */
            prompt: string;
            /** Prompt Group */
            prompt_group?: string | null;
            /** Rank Position */
            rank_position?: number | null;
            /** Reasoning Trace */
            reasoning_trace?: {
                [key: string]: unknown;
            } | null;
            /** Recommendation Reasoning */
            recommendation_reasoning?: string | null;
            /**
             * Response Id
             * Format: uuid
             */
            response_id: string;
            /** Schema Version */
            schema_version?: string | null;
            /** Search Provider */
            search_provider?: string | null;
            /** Search Results */
            search_results?: unknown[] | {
                [key: string]: unknown;
            } | null;
            /** Search Visibility */
            search_visibility?: {
                [key: string]: unknown;
            } | null;
            /** Sector */
            sector?: string | null;
            /** Sentiment */
            sentiment?: string | null;
            /** Simulated Answer */
            simulated_answer?: string | null;
            /** Trust Signals */
            trust_signals?: unknown[] | null;
            /** Visibility Drivers */
            visibility_drivers?: {
                [key: string]: unknown;
            } | null;
            /** Visibility Gaps */
            visibility_gaps?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description Credentials required to authenticate a user.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description Authenticated user and bearer token returned after login.
         */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            user: components["schemas"]["UserOut"];
        };
        /**
         * OrganizationOut
         * @description The organization a request is acting within.
         */
        OrganizationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
        };
        /** PromptOut */
        PromptOut: {
            /** Category */
            category: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text */
            text: string;
        };
        /**
         * RefreshResponse
         * @description New bearer token returned after refresh-token rotation.
         */
        RefreshResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** ResponseOut */
        ResponseOut: {
            /** Audit */
            audit?: {
                [key: string]: unknown;
            } | null;
            /** Cost Usd */
            cost_usd: number;
            /** Engine */
            engine: string;
            /** Footprint */
            footprint: boolean | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Matched Snippet */
            matched_snippet: string | null;
            /** Model */
            model: string;
            /**
             * Prompt Id
             * Format: uuid
             */
            prompt_id: string;
            /** Raw Text */
            raw_text: string;
        };
        /** ResultOut */
        ResultOut: {
            /** Citation Summary */
            citation_summary?: {
                [key: string]: unknown;
            } | null;
            /** Competitors Appeared */
            competitors_appeared: components["schemas"]["CompetitorMention"][] | null;
            /** Engine Presence */
            engine_presence: components["schemas"]["EnginePresence"][] | null;
            /** Footprint Count */
            footprint_count: number | null;
            /**
             * Geo Records
             * @default []
             */
            geo_records: components["schemas"]["GeoRecordOut"][];
            /** Geo Score */
            geo_score: number | null;
            /** Interventions */
            interventions?: {
                [key: string]: unknown;
            }[] | {
                [key: string]: unknown;
            } | null;
            /** Kyc */
            kyc: {
                [key: string]: unknown;
            } | null;
            /** Prompts */
            prompts: components["schemas"]["PromptOut"][];
            /** Reliability Score */
            reliability_score?: number | null;
            /** Responses */
            responses: components["schemas"]["ResponseOut"][];
            seo: components["schemas"]["SeoAuditOut"] | null;
            serp: components["schemas"]["SerpVisibilityOut"] | null;
            /** Total Responses */
            total_responses: number | null;
        };
        /**
         * SeoAuditOut
         * @description The SEO audit for one analysis (ADR-31).
         *
         *     ``grade`` is the headline rather than ``score``, because a weighted average
         *     can hide a fatal problem: the grade is capped by critical failures, so a site
         *     that blocks AI crawlers cannot present as healthy. Null on runs that did not
         *     audit — a checker submission has no site to look at.
         */
        SeoAuditOut: {
            /** Checks */
            checks: components["schemas"]["SeoCheckOut"][];
            /** Grade */
            grade: string | null;
            /** Score */
            score: number | null;
            /** Status */
            status: string;
        };
        /**
         * SeoCheckOut
         * @description One SEO / AI-readiness check and the evidence behind its verdict.
         *
         *     ``status`` is one of ``pass`` / ``warn`` / ``fail`` / ``not_measured`` /
         *     ``not_applicable``. The last two are excluded from the score and mean
         *     different things — "we could not read the input" versus "this does not apply
         *     here" — so the UI must not collapse them into each other or into a failure.
         */
        SeoCheckOut: {
            /** Check Id */
            check_id: string;
            /** Detail */
            detail: string | null;
            /** Evidence */
            evidence: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** SeoProjectDetailOut */
        SeoProjectDetailOut: {
            /** Audits */
            audits: components["schemas"]["SiteAuditSummaryOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Domain */
            domain: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            latest_audit: components["schemas"]["SiteAuditSummaryOut"] | null;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SeoProjectOut */
        SeoProjectOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Domain */
            domain: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            latest_audit: components["schemas"]["SiteAuditSummaryOut"] | null;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SerpCheckOut
         * @description One search query run for an analysis, and what the results page showed.
         *
         *     ``hit`` is nullable and the distinction matters to anyone reading this: NULL
         *     is a page we could not read (the search instance was unreachable, or every
         *     upstream engine refused it) and is excluded from the score; ``false`` is a
         *     real, counted miss.
         */
        SerpCheckOut: {
            /** Hit */
            hit: boolean | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Matched Snippet */
            matched_snippet: string | null;
            /** Matched Url */
            matched_url: string | null;
            /** Matched Via */
            matched_via: string | null;
            /** Query */
            query: string;
            /** Rank */
            rank: number | null;
            /** Result Count */
            result_count: number;
            /** Source */
            source: string;
            /** Unresponsive Engines */
            unresponsive_engines: string | null;
        };
        /**
         * SerpVisibilityOut
         * @description SERP visibility for one analysis (ADR-28).
         *
         *     Present only on runs where the feature was switched on; ``ResultOut.serp``
         *     stays null otherwise, so "we did not look" is never rendered as a zero.
         *     ``score`` is separately nullable *within* a present summary: that is the run
         *     where we did look and could not read the results.
         */
        SerpVisibilityOut: {
            /** Checks */
            checks: components["schemas"]["SerpCheckOut"][];
            /** Hits */
            hits: number;
            /** Queries */
            queries: number;
            /** Score */
            score: number | null;
            /** Source */
            source: string | null;
            /** Status */
            status: string;
        };
        /**
         * SignupRequest
         * @description Credentials required to create a user account.
         *
         *     ``account_type`` decides what kind of organization the new user gets. Both
         *     kinds are real organizations with the same machinery behind them — an
         *     individual is not a special case with less structure, it is a company of
         *     one. That is what makes "convert to a team account" a rename plus an
         *     invitation rather than a data migration.
         */
        SignupRequest: {
            /**
             * Account Type
             * @default individual
             * @enum {string}
             */
            account_type: "individual" | "organization";
            /** Email */
            email: string;
            /** Organization Name */
            organization_name?: string | null;
            /** Password */
            password: string;
        };
        /** SiteAuditDetailOut */
        SiteAuditDetailOut: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Step */
            current_step: ("discovery" | "crawl" | "analysis" | "finalize") | null;
            /** Error */
            error: string | null;
            /** Health Score */
            health_score: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Js Rendering */
            js_rendering: boolean;
            /** Page Limit */
            page_limit: number;
            /** Pages */
            pages: components["schemas"]["SiteAuditPageOut"][];
            /** Pages Crawled */
            pages_crawled: number;
            /** Pages Discovered */
            pages_discovered: number;
            /**
             * Profile Id
             * @enum {string}
             */
            profile_id: "site_audit_mobile" | "site_audit_desktop";
            /** Progress */
            progress: number;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed";
            /** Total Errors */
            total_errors: number;
            /** Total Notices */
            total_notices: number;
            /** Total Warnings */
            total_warnings: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SiteAuditIssueOut */
        SiteAuditIssueOut: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning" | "notice";
        };
        /** SiteAuditPageOut */
        SiteAuditPageOut: {
            /** Final Url */
            final_url: string;
            /** H1 Count */
            h1_count: number;
            /** Html Lang */
            html_lang: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issues */
            issues: components["schemas"]["SiteAuditIssueOut"][];
            /** Meta Description */
            meta_description: string | null;
            /** Requested Url */
            requested_url: string;
            /** Schemas */
            schemas: components["schemas"]["SiteAuditSchemaOut"][];
            /** Status Code */
            status_code: number;
            /** Title */
            title: string;
        };
        /** SiteAuditSchemaDetailsOut */
        SiteAuditSchemaDetailsOut: {
            /** Invalid Fields */
            invalid_fields?: string[];
            /** Valid Fields */
            valid_fields?: string[];
        };
        /** SiteAuditSchemaOut */
        SiteAuditSchemaOut: {
            details?: components["schemas"]["SiteAuditSchemaDetailsOut"];
            /** Error Detail */
            error_detail?: string | null;
            /** Structure Status */
            structure_status: string;
            /** Syntax Valid */
            syntax_valid: boolean;
            /** Type */
            type: string;
        };
        /** SiteAuditSettingsRequest */
        SiteAuditSettingsRequest: {
            /**
             * Js Rendering
             * @default true
             */
            js_rendering: boolean;
            /**
             * Page Limit
             * @default 10
             */
            page_limit: number;
            /**
             * Profile Id
             * @default site_audit_mobile
             * @enum {string}
             */
            profile_id: "site_audit_mobile" | "site_audit_desktop";
        };
        /** SiteAuditSummaryOut */
        SiteAuditSummaryOut: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Step */
            current_step: ("discovery" | "crawl" | "analysis" | "finalize") | null;
            /** Error */
            error: string | null;
            /** Health Score */
            health_score: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Js Rendering */
            js_rendering: boolean;
            /** Page Limit */
            page_limit: number;
            /** Pages Crawled */
            pages_crawled: number;
            /** Pages Discovered */
            pages_discovered: number;
            /**
             * Profile Id
             * @enum {string}
             */
            profile_id: "site_audit_mobile" | "site_audit_desktop";
            /** Progress */
            progress: number;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed";
            /** Total Errors */
            total_errors: number;
            /** Total Notices */
            total_notices: number;
            /** Total Warnings */
            total_warnings: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * UserOut
         * @description Public user fields returned by authentication endpoints.
         */
        UserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WaitlistRequest
         * @description A public waitlist signup. The email is validated + normalized server-side
         *     (trim + lowercase) so a malformed address is a 422 before any row is written,
         *     and the stored value matches the unique lowercased column.
         */
        WaitlistRequest: {
            /** Email */
            email: string;
        };
        /** WaitlistResponse */
        WaitlistResponse: {
            /** Ok */
            ok: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_members_api_v1_admin_members_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: string | null;
                role?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_member_api_v1_admin_members__user_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_api_v1_admin_members__user_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminMemberUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_organization_api_v1_admin_organization_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrganizationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_analysis_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_analysis_api_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserOut"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_checker_api_v1_checker_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckerSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckerSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_checker_lead_api_v1_checker_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckerLeadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_seo_projects_api_v1_seo_projects_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeoProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_seo_project_api_v1_seo_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSeoProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeoProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_seo_project_api_v1_seo_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeoProjectDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_site_audit_api_v1_seo_projects__project_id__audits_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteAuditSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteAuditSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_site_audit_api_v1_seo_projects__project_id__audits__audit_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
            };
            path: {
                project_id: string;
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteAuditDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_waitlist_api_v1_waitlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
