'use client'

import { useState } from 'react'
import type { IndustryQuestionResponse } from '@/lib/industry-citations'

export default function IndustryQuestionsEditor({
  sample,
  editable,
}: {
  sample: IndustryQuestionResponse
  editable: boolean
}) {
  const [questions, setQuestions] = useState(sample.questions)
  const normalized = questions.map((question) =>
    question
      .normalize('NFKC')
      .toLocaleLowerCase()
      .replace(/[^\p{L}\p{N}]/gu, ''),
  )
  const duplicate = new Set(normalized).size !== normalized.length
  const invalid = questions.some(
    (question) => question.trim().length < 10 || question.trim().length > 500,
  )

  return (
    <section
      aria-label="Industry questions"
      className="mt-6 rounded-xl border border-surface-border bg-white p-6"
    >
      <h2 className="text-lg font-semibold">
        {editable ? 'Review your questions' : 'Your generated questions'}
      </h2>
      <p className="mt-2 text-sm text-surface-subtle">
        {sample.industry} · {sample.country} · {sample.language.toUpperCase()}
      </p>
      <p className="mt-2 text-sm text-surface-subtle">
        {editable
          ? 'Edit, add or remove questions. Keep 1–20 distinct questions, each 10–500 characters.'
          : 'This workflow uses the generated questions without an editing step.'}
      </p>
      <ol className="mt-5 space-y-4">
        {questions.map((question, index) => (
          <li
            key={index}
            className="rounded-lg border border-surface-border p-3"
          >
            {editable ? (
              <>
                <label
                  htmlFor={`question-${index}`}
                  className="text-sm font-medium"
                >
                  Question {index + 1}
                </label>
                <textarea
                  id={`question-${index}`}
                  value={question}
                  maxLength={500}
                  rows={2}
                  aria-invalid={
                    question.trim().length < 10 ||
                    normalized.indexOf(normalized[index]) !== index
                  }
                  onChange={(event) =>
                    setQuestions((current) =>
                      current.map((value, position) =>
                        position === index ? event.target.value : value,
                      ),
                    )
                  }
                  className="mt-2 w-full rounded-lg border border-surface-border p-3 text-sm focus:outline-none focus:ring-2 focus:ring-signal"
                />
                <button
                  type="button"
                  disabled={questions.length <= 1}
                  onClick={() =>
                    setQuestions((current) =>
                      current.filter((_, position) => position !== index),
                    )
                  }
                  className="mt-1 text-sm underline disabled:opacity-40"
                  aria-label={`Remove question ${index + 1}`}
                >
                  Remove
                </button>
              </>
            ) : (
              <p className="text-sm">
                {index + 1}. {question}
              </p>
            )}
          </li>
        ))}
      </ol>
      {editable ? (
        <button
          type="button"
          disabled={questions.length >= 20}
          onClick={() => setQuestions((current) => [...current, ''])}
          className="mt-4 rounded-lg border border-surface-border px-4 py-2 text-sm disabled:opacity-40"
        >
          Add question
        </button>
      ) : null}
      <p role="status" className="mt-4 text-sm">
        {questions.length} questions
        {invalid ? ' · Each question must contain 10–500 characters.' : ''}
        {duplicate ? ' · Remove or edit duplicate questions.' : ''}
      </p>
      <p className="mt-4 text-xs text-surface-subtle">
        Generated by {sample.model}. This sample may need review for relevance
        and language. Changes stay on this page and reset on reload.
      </p>
      <button
        type="button"
        disabled
        className="mt-5 rounded-lg bg-ink px-5 py-2.5 text-sm text-white opacity-40"
        aria-describedby="analysis-pending"
      >
        Start analysis
      </button>
      <p id="analysis-pending" className="mt-2 text-sm text-surface-subtle">
        Analysis execution is the next step and is not connected yet. No answers
        or citation rankings have been collected.
      </p>
    </section>
  )
}
